### ISSUE TITLE
BlockPuller bug: Node_MessageReceived

### ISSUE THREAD

**Issue by Derrick-** [stratisproject/StratisBitcoinFullNode#102]
Node_MessageReceived threw this exception:

![image](https://cloud.githubusercontent.com/assets/3766117/24725540/50277eb2-1a1d-11e7-8280-382ba1bf4413.png)

Locals:
![image](https://cloud.githubusercontent.com/assets/3766117/24725487/1f37cf78-1a1d-11e7-94f6-80b283a0e561.png)

Console:
![image](https://cloud.githubusercontent.com/assets/3766117/24725549/64428dc4-1a1d-11e7-8dc8-aae04e681d7d.png)

Please let me know if there's any more information I can provide to help troubleshoot this.

**Comment by Derrick-** [comment]
More locals:
![image](https://cloud.githubusercontent.com/assets/3766117/24725700/d3f5ffca-1a1d-11e7-8fd7-4280eb9ab72d.png)

**Comment by dangershony** [comment]
Thanks wowoo I never expected that exception to throw, map should not be empty.

**Comment by dangershony** [comment]
Ah unless there is a race condition where a node got disconnected and received a block simultaneously.

**Comment by Derrick-** [comment]
Maybe. Map is not empty.

![image](https://cloud.githubusercontent.com/assets/3766117/24726056/07926fa2-1a1f-11e7-9fde-fb0784eaa600.png)

**Comment by dangershony** [comment]
Yeah not empty but jas a removed pending vector, would be interesting to know if the node is in a disconnected state

**Comment by dangershony** [comment]
I don't think locking is the solution it's already concurrent the dictionary right?

**Comment by Derrick-** [comment]
I belive ConcurrentDictionary.TryRemove() can fail for concurrency reasons, in which case the operation could possibly be retried with success, but I'm not (yet) familiar enough with this process to give any recommendations.

**Comment by Derrick-** [comment]
This does look like a concurrency problem to me, noting that at the point of exception, this.pendingDownloads does contain the key {000000000000000000ce3664bac8347ec29a8bcf5fcf004acb04fafef9ba1fef} which was successfully removed.

![image](https://cloud.githubusercontent.com/assets/3766117/24728821/97f92c0c-1a29-11e7-8c2f-7dce760fda92.png)

Looks to me like it was readded after it was removed, and two threads tried to hit map at the same time.

**Comment by Derrick-** [comment]
If no objection, I'll at least draft up SemaphoreSlim protection on all node events that fit this pattern.

SemaphoreSlim should incur well less than a microsecond of overhead here.

**Comment by bokobza** [comment]
Just had the same error so here's some more data.

map is empty
![image](https://cloud.githubusercontent.com/assets/1867877/24746882/85ba915a-1ab2-11e7-8e14-0bdba6b5ccf9.png)

state of the console
![image](https://cloud.githubusercontent.com/assets/1867877/24746925/9a06bdaa-1ab2-11e7-93fd-18b278d456d8.png)

stack
![image](https://cloud.githubusercontent.com/assets/1867877/24747060/0e9ec7fc-1ab3-11e7-87ec-8af989de183b.png)

locals 2
![image](https://cloud.githubusercontent.com/assets/1867877/24746954/b21a5de8-1ab2-11e7-89fe-45756cae9b3b.png)

**Comment by dangershony** [comment]
@Derrick- your last print screen is really odd, this suggests the concurrent dictionary didn't remove the item. unused has a value and also the dictionary not sure how that could happen..

Jeremy you got the same bug, that's odd has anything changed recently in this file?

**Comment by bokobza** [comment]
I had been running the node for a few hours when it happened. 
Will keep my eyes peeled for attached_node :-)

**Comment by Derrick-** [comment]
> unused has a value and also the dictionary not sure how that could happen..

I went through this quite a bit. I believe it can happen because once it's removed it allows another thread to begin a pull: re-adding it. 

I believe this logic must prevent another thread from checking the pending downloads while the new block is being processed. I think either semaphores or dispatching to a single block processing thread is indicated here.

**Comment by dangershony** [comment]
I agree that NodeConnections can be refactored ideally to be thread agnostic using the async framework.
But thats a really big task (we will get to it one day) and it will still have concurrency. 

We are using concurrent dictionaries I believe all our thread logic can be handled that way.
Adding semaphores kind of removed the need to use the ConcurrentDictionary (where locks are used already internally)

**Comment by Derrick-** [comment]
I'm also finding that blockpuller eventually stalls, and I my hunch is that it's related to an inconsistency in BlockPuller.map and BlockPuller.pendingDownloads.

And example of the problem is here:

```
			internal void Release(uint256 blockHash)
			{
				BlockPullerBehavior unused;
				uint256 unused2;
				if(this.puller.map.TryRemove(blockHash, out unused))
				{
					this.pendingDownloads.TryRemove(blockHash, out unused2);
					this.puller.pendingInventoryVectors.Add(blockHash);
				}
			}

			internal void StartDownload(uint256 block)
			{
				if(this.puller.map.TryAdd(block, this))
				{
					this.pendingDownloads.TryAdd(block, block);
					AttachedNode.SendMessageAsync(new GetDataPayload(new InventoryVector(AttachedNode.AddSupportedOptions(InventoryType.MSG_BLOCK), block)));
				}
			}

```
Where it is possible for 2 threads to be running these functions interleaved in such a way as to create an inconsistent state within the collections, which may result in permanent inability to download a particular block (theorized only because of my experience with stalled IBD).

I think all access to the pendingDownloads and map collections need to be synchronized, or the data within these collections needs to be combined if possible into a single concurrent data object.

**Comment by Derrick-** [comment]
New theory.
Looks like BlockPullerBehavior.AttachCore is being called twice.
![image](https://cloud.githubusercontent.com/assets/3766117/25107186/cb86b852-239b-11e7-9f1b-7f2b877e37b5.png)

**Comment by dangershony** [comment]
Yes this is expected behaviour, the behaviours are used both for consensus and store.

Sometimes the nodes stall it can be network or the peer or what ever it very hard to find where the stalling comes from so we cannot be easily sure its the puller. To good out you need to add lots of debug output.

But I think your idea of a shared resource is not bad, we can consider having only one concurrent dictionary that has all the download info and is shared to every behaviour. Then there won't be any race condition between dictionaries.

We need to think carefully of that design.

**Comment by Aprogiena** [comment]
All these invariants have to be in comments of the properties. For example, BlockPullerBehavior.Node_MessageReceived clearly states that:

IF BlockPullerBehavior.pendingDownloads contains a block hash (C1) AND the node can receive BlockPayload message that contains the hash (C2), THEN BlockPuller.map has to contain the hash as well (R1). This is very non-trivial bind between BlockPuller and BlockPullerBehavior and it is hard to check the code if that always hold. 

C1 means we have to examine adding to pendingDownloads and removals from map. 

Adding to pendingDownloads happens only in StartDownload(uint256) and StartDownload(GetDataPayload). StartDownload(uint256) satisfies R1 immediately. StartDownload(GetDataPayload) does not satisfy R1, but it is only called from DistributeDownload, which does satisfy R1.

Removing from BlockPuller.map happens in BlockPullerBehavior.Node_MessageReceived, which does not violate R1. Then it happens in BlockPullerBehavior.Release, which does not violate R1.

C2 seems irrelevant in all cases.

As the all code paths respect the invariant, the only possible resolution is the race condition, which is indeed possible. All it takes is for one thread to execute pendingDownloads.TryRemove in BlockPullerBehavior.Node_MessageReceived and once this is done, another thread calls BlockPullerBehavior.Release and executes puller.map.TryRemove.

I'd discourage using Concurrent structures as they tend to produce this kind of problems because you think you are safe because you are using concurrent structure ... 

I'm happy to fix this race condition, but to do so, we need to identify all the invariants between all the properties we are using - map, pendingInventoryVectors, DownloadedBlocks and pendingDownloads. These have to be documented properly in the comments so that I can write the fix and not to forget about another relation among those guys. Also the comments should help the reviewer to the check the fix satisfies everything needed.
