### ISSUE TITLE
Potential service denial attack because we have no max inbound connections limit

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1054]
We don't have a max inbound connections limit so I guess it's possible to perform a service denial attack on a C# node.

Also NetworkPeerServer: Listen(int maxIncoming = 20)
max limit is actually not used. 

In bitcoin core they have a default limit of 125 connections so I suggest doing it the same.

**Comment by noescape00** [comment]
>reject new connection from the same IP address if we have already Y connections from it

What about IPv6 addresses? An attacker can easily have a TON of them.

**Comment by Aprogiena** [comment]
It is not an issue really.DoS attacks are usually considered only if the attacker uses less resources than the target.which is not the case here.but I have described the defence against it anyway in one of the issues earlier but it is probably needed.

the defence mechanism is based on bans of ranges of IPs which size is doubled every time another incident is detected from IP address that is not currently banned but is in the extended range

but still I consider this nonissue

so what I suggested is more of the protection against misbehaving note because it is faulty not because it is malicious
