### ISSUE TITLE
ConsensusLoop race condition

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1262]
```
if (this.Tip.ChainWork > this.Chain.Tip.ChainWork)
{
    // This is a newly mined block.
    this.Chain.SetTip(this.Tip);
    this.Puller.SetLocation(this.Tip);

    this.logger.LogDebug("Block extends best chain tip to '{0}'.", this.Tip);
}
```

Here after the if is evaluated to `true` it is possible that a peer sends us a better chain and we switch to it and after that inner body of the if statement is executed.

Also a race condition is possible for line 400: `this.Chain.SetTip(this.Tip);` (ask @Aprogiena about it)

**Comment by dangershony** [comment]
I think this code is only executed when the node is mining.
Whats the consequence of such a race condition?

**Comment by noescape00** [comment]
>Whats the consequence of such a race condition?

**Comment by Aprogiena** [comment]
Yes, it is kind of a problem that maybe is not critical, because it is quite likely that in most cases the node will recover from it.

But it is immediate sign of wrong design, specifically concurrent chain. So it is just another reminder that concurrent chain should be redesigned. In the last PR that Ivan submitted, we tried to move all logic that changes the concurrent chains tip into the new component. But it was not entirely possible because of these guys in consensus loop.

Unfortunately it is not possible to fix these properly without some update to concurrent chain, but better redesign it completely with sessions and blackjack.

**Comment by bokobza** [comment]
@Aprogiena can we close this or not yet? Or is there any other issue we should link this to?

**Comment by Aprogiena** [comment]
not yet, we have it on the list

**Comment by noescape00** [comment]
Fixed with activation merge.
