### ISSUE TITLE
Api project (and RPC) to allow ssl endpoints

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1263]
The ssl key can be a stored as a file in disk with special permissions.

**Comment by majikandy** [comment]
In order to avoid in flight data compromise
As an api consumer
I want all requests over https with a trusted certificate

*feature complete when*
- http calls return 307 temporary redirect
- all api calls require https
- a valid certificate is used
- api is on https on docker too (edited)

First Reviewer  @monsieurleberre 
Second Reviewer (merger) @bokobza 
(please thumbs up this if you approve the acceptance criteria)

**Comment by bokobza** [comment]
**It appears that support for SSL in RPC has been completely dropped in bitcoin.**

[SSL support for RPC dropped](https://github.com/bitcoin/bitcoin/blob/d6a92dd0ea42ec64f15b81843b4db62c7b186bdb/doc/release-notes.md#ssl-support-for-rpc-dropped)
[Why is JSON-RPC over SSL “strongly discouraged”?](https://bitcoin.stackexchange.com/questions/39117/why-is-json-rpc-over-ssl-strongly-discouraged)
[Enabling SSL on original client daemon](https://en.bitcoin.it/wiki/Enabling_SSL_on_original_client_daemon)

I suggest we don't do it in our node and this task has the "(and RPC)" removed from its title.

There is an argument there to say that if we remove SSL for RPC then we should also remove it for the API.
Thoughts?
@monsieurleberre @Aprogiena @dangershony

**Comment by Aprogiena** [comment]
As I said before, I don't know why are we doing SSL. But if something makes sense, it is doing it for API because there we are actually sending password. So unless we switch to one-time tokens, and as long as we want to allow people to connect remotely to API, it makes sense to protect it. However, the argument on the bitcoin side is also strong because SSL is a big overkill for this task. There is a many years of history of super serious bugs inside of SSL and especially some implementations. This means that by implementing SSL for API, we will suddenly be open to large number of attacks that we can expect to be discovered in the future. I don't think we should do SSL now because people will not access API remotely anyway. Later we can come up with solutions without SSL.

**Comment by bokobza** [comment]
Closed with #1897
