### ISSUE TITLE
[RF] Extend chained header 

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1320]
Extend chained header with pointer to the block data and information about block state.

**Comment by noescape00** [comment]
There will be 2 new properties that will be contained in the ChainedHeader. They are only in-memory and are not persisted to the hard drive:

1. Pointer to the Block instance that this header is representing. Can be Null in case we don't have a block data downloaded. 
2. BlockState (a new enum should be introduced). 

BlockState enum: 

- HeaderOnly - we only have a header of the block and the header is valid (after we introduce ProvenHeader this state means that we have valid proven header).
- BlockDataRequired - state that means that we are interested in downloading a block that is being represented by that header. This happens when header is a part of the chain that can potentially replace our consensus tip because its tip's total chainwork is greater comparing to what we currently have.
- BlockDataAvailable- we have block data for the header.
- PartiallyValidated
- FullyValidated
-
