### ISSUE TITLE
[RF] Create chained header tree component

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#1321]
Create chained header tree component and define Max interest gap. 
Create basic methods of this component and at unit tests.
- Chained header tree is a tree of all chains that we can see.
- Consider resolving issue 1156 during the design.

**Comment by noescape00** [comment]
ChainedHeaderTree design:

## Private data structures:
- PeerTipsByHash: dictionary[hash - List of peer ids]
- ChainHeadersByHash: dictionary[hash - chainedBlock]

## Methods:

### CT changes (advances or reorgs):
Check every peer.tip against max reorg (using PeerTipsByHash and finding forkpoint(CT, tip)). If violated - discard tip, do CHB.PendingTip=null & CHB.TrySync, but dont disconnect or ban (be carefull in situation when we check peer.tip and at the same time new headers are presented)


### HeadersPresented
	1) If headers[0].PrevHash is not in the ChainHeadersByHash - return (Can't connect)
	2) Find using ChainHeadersByHash if some of the headers are already created and validated
	   For new headers- start creating and appending new ChainHeaders one by one. Validate each (if its not possible due to insufficency - return). First new header should be checked against max reorg (by finding forkpoint(CT, tip)) - If violated - discard tip; return
	   When new ChainHeader is created it should be added to previous.Next list
	3) Add tip to PeerTipsByHash (claim new tip)
	4) call RemoveChainClaim(peer.Id, peer.OldTip)
	5) Check work(tip) against work(CT) and mark tip's chain as DataRequired if it's better (report to BM if new data required)
	
	returns:
	* Max reorg violated (caller should disconnect, ban) - Exception
	* Can't connect (caller should request new headers) - Exception
	* New data marked DataRequested (caller should pass it to the block puller)	&&& how many headers were consumed (those that were not are insufficient)

### Peer disconnect
	RemoveChainClaim(peer.Id, peer.Tip)

### private RemoveChainClaim (peerId, peerTip):
	currentHeader = peerTip;

	while(true)
		nextExists = currentHeader.Next.Lenght != 0
		listOfPeersClaimingThisHeader = PeerTipsByHash[currentHeader]

		isEmpty = false;

		if (listOfPeersClaimingThisHeader != null)
			if (peerId == ANY_PEER)
				listOfPeersClaimingThisHeader.Clean()
			else
				listOfPeersClaimingThisHeader.Remove(peerId)

			if (listOfPeersClaimingThisHeader.Lenght == 0)
				PeerTipsByHash.Remove(currentHeader)
				isEmpty = true;
		else
			isEmpty = true;

		if (!isEmpty || nextExists)
			break

		ChainHeadersByHash.Remove(currentHeader)
		currentHeader.Prev.Next.Remove(currentHeader)		 

		currentHeader = currentHeader.Prev;


### OnDataAquired(block, out ChainedBlock) - BM will call that after it pulls data from the BlockPuller
	Set chaind block associated with the block data = downloaded and link the block data
	returns true if partial validation required
		returns true if prev block state == partial | fully validated
	returns false if partial validation not required
	throws if cant associate with any header

### OnPartialValidationSucceeded(ChainedHeader, out bool wannaReorg = false)
	check if ChainedHeader is still in tree (ChainedHeader.Prev.Next.Contains(ChainedHeader))
		if not return.
	ChainedHeader.ValidationState = PV
	check if ChainedHeader.ChainWork > CT.ChainWork. If true
		PeerTipsByHash.Add(ChainedHeader, US_CONSTANT)
		wannaReorg = true
	go through ChainedHeader.Next and return list of headers which state is = DataAvailable (so the caller can start partial validation)


### OnFullValidationSucceeded
	ChainedHeader.ValidationState = FV

### OnPartialOrFullValidationFailed(ChainedHeader)
	recursively call RemoveChainClaim(ANY_PEER, currentHeader) for every .Next untill there is no next. And before calling that check if any peer claims that tip and if it does- add it to the special list PeersToBan.
	returns PeersToBan (they will be banned)


notes:
	for every data structure (PeerTipsByHash, ChainHeadersByHash) and ChainedBlocks from the tree modifications we suggest introducing a lock for each


Created and discussed with @Aprogiena

**Comment by noescape00** [comment]
Tests: 


1) Supply headers where first header can't be connected- should throw
2) Supply headers that we already have, make sure no new ChainedHeaders were created
3) Supply some headers and after that supply some more headers and make sure that PeerTipsByHash is updated (at the total amount of items is the same)
4) Supply headers where half of them are new and half are old- make sure that ChainedHeader was created for new ones
5) 3 peers should supply headers so one of the peers is on a fork. Make sure that ChainedBlock is not created more than once for the same header. Check that next pointers were created correctly
6) Make sure checkpoints are off- supply some headers, CHT should return ToDownload array of the same size as the amount of headers. 
7) We have a chain, someone presents an invalid header. After that our chain's last block shouldn't change and it shouldn't have .Next and it throws
8) We have a chain and peer B is on the best chain. After that peer C presents an alternative chain with a forkpoint below B.Tip. After that peer A prolongs C's chain (but he sends all headers from the fork point) with few valid and one invalid. 
	Make sure that C's chain is not removed, only headers after that. 
9) Check that everything is always consumed
10) When checkpoints are enabled and the only checkpoint is at block X, when we present headers before that- none marked for download. When we first present checkpointed header and some after- all previous are also marked for download & those that are up to the last checkpoint are marked as assumevalid
11) When checkpoints are enabled and the first is at block X, when we present headers before that- none marked for download. When we first present checkpointed header and some after- only headers before the first checkpoint (including it) are marked for download
12) Checkpoints are disabled, assumevalid at block X, headers up to block X + some more are presented, make sure all up to AssumeValid are marked for download and assume valid
13) Chain 1 is presented- it is marked for download. Consensus tip is now set to the tip of A. After that chain B with the fork point in the middle of A is presented- it has less chainwork so it's not marked for download. Now B is prolonged greatly and it is marked for download because it has more chainwork.

**The list will be updated.**

**Comment by dangershony** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/issues/1156

**Comment by noescape00** [comment]
Fixed with activation merge.
