### ISSUE TITLE
Initialized readonly field in a smart contract causes null reference.

### ISSUE THREAD

**Issue by codingupastorm** [stratisproject/StratisBitcoinFullNode#1699]
When creating the following contract, a NullReferenceException occurs as the contract tries to spendgas in a method that occurs before the constructor is executed (I believe).

```
public class Auction : SmartContract
{
	private readonly string test = "Slugman's test: ";

	public Auction(ISmartContractState smartContractState, ulong durationBlocks)
		: base(smartContractState)
	{
	}
}
```

@rowandh may have more to say about this.

**Comment by rowandh** [comment]
This occurs due to an invalid assumption in `SmartContractGasInjector` about the presence of opcodes invoking the base constructor. A readonly field will be set before the base constructor is invoked.

Consider this class:
```
public class Test
{
	public readonly int Num = 1;
}
```

The generated IL is:
```
IL_0000:  ldarg.0     
IL_0001:  ldc.i4.1    
IL_0002:  stfld       UserQuery+Test.Num
IL_0007:  ldarg.0     
IL_0008:  call        System.Object..ctor
IL_000D:  nop         
IL_000E:  ret
```

We should look into pattern-matching the base constructor call instead.
