### ISSUE TITLE
Try to isolate responsibilities from the ConsensusManager

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/StratisBitcoinFullNode#1862]
Part of #1736

This class is currently doing a few too many things, as a first cut I see 2 groups responsibilities that lay themselves well for separation

First group is
- download and request blocks

Second group something like
- validate chains / headers
- select tip candidates
- rewind/reconnect chains

#### Acceptance Criteria:
This is done when we have extracted a class and its interface, of which the sole purpose is to handle the download of the blocks, from the ConsensusManager

**Comment by fassadlr** [comment]
@monsieurleberre I'm reopening this as I feel that `ConsensusManager` can still be looked at some point to extract some logic as it is a massive class sharing too many responsibilities.

**Comment by fassadlr** [comment]
This is a continuation on the discussion in PR #1911.

@noescape00 My idea with the visitor pattern was to isolate parts of CM so that we can individually test them. A good example would be `BlockMined`.

@dangershony mentioned that the biggest role of CM is to ensure that locks are taken when changes are made to the CHT. So this is very good use case. If my understanding is correct, we don't want anything else apart from CM to be responsible for making changes to CHT because CM manages locks around it.

So how do we isolate code in CM that does specific things to CHT so that we can test them in isolation? We dont want to have to start a whole new instance of CM every time we want to have test, for example, `BlockMined`.

The test cases you wrote for `BlockMined` proves my point that they arent actually that complicated but somehow it appears to be difficult to isolate the logic from CM.

This is why I envisioned a scenario where you have isolated pieces of logic that is allowed to make changes to CHT and ONLY via CM's locks. So essentially CM becomes a lock manager class of sorts. This is why I thought that a class called BlockMined "visits" CM, makes changes to CHT internally and exits.

@Aprogiena raised a valid point of not wanting to make CHT public in CM. I agree with this, so how do we solve this problem? How can an isolated piece of logic makes changes to CHT internally, without exposing CHT to the outside?

If we can solve this, we future proof CM to be pluggable with isolated pieces of code that can make changes CHT. I.e. if in the future we have another scenario where have to affect CHT via CM, we can just build another class that we can pass to CM, it executes, and voila, you have made changes to CHT

Lets think of a scenarios where this can be possible! 👍

**Comment by dangershony** [comment]
Hi guys the tests for CM will be pushed as last task, I am also not completely happy with CM itself and the amount of responsibilities it has, essentially CM should actually be a ConsensusScheduler or ConsensusSynchronization and be the place where all synchronization with the consensus advancement will take place (as Fassa suggested downloading blocks can happen in another interface.
The reason to delay tests I that once we build them they will be closely bound to CM and harder to change, and we anyway test CM with integration tests.

**Comment by Aprogiena** [comment]
@dangershony I highly suggest we finish the component and make it working and secure before we think about splitting responsibilities. Most importantly we need the component working, everything else is just nice to have. It does not matter if the tests are closely bound, if they help us verify the implementation, it is exactly what we need.

**Comment by Aprogiena** [comment]
> We dont want to have to start a whole new instance of CM every time we want to have test, for example, BlockMined.

@fassadlr Why?

**Comment by fassadlr** [comment]
There is no requirement for this at this point in time.
