### ISSUE TITLE
[Activation] PowBlockDefinition - ensure we are calling validator correctly

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1934]
There is a TODO in PowBlockDefinition.cs, fix it

**Comment by herbepau** [comment]
Following a discussion with Ivan and Apro, it was determined that the method TestBlockValidity is not required and can be removed from the codebase.  This is because block validation is already happening during the mining phase in ConsensusManager.
Also, this is a sanity check and should never happen, and that not removing it from here would lead to performing partial validation twice.

**Comment by bokobza** [comment]
fixed with https://github.com/stratisproject/StratisBitcoinFullNode/pull/1987
