### ISSUE TITLE
[Activation] tests for consensus manager

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#1937]
See test cases here: https://github.com/stratisproject/Research/blob/master/CoreSyncingAndProvenHeaders/ConsensusManager.txt

**Comment by dangershony** [comment]
==================================================TESTS==================================================

=====HeadersPresented
1) Setup blockPuller.AverageBlockSize = 200 bytes. Checkpoints are disabled. 10 new headers are presented. Now BP has a peer tip at the last header (BP.NewTipClaimed is called with the last header), BP is asked to download 10 blocks (BP.RequestNewData called). Make sure that expectedBlockDataBytes equals to 200*10. Make sure that hashes of those 10 headers are inside expectedBlockSized list. Make sure that peer that was supplied was added to peersByPeerId.
2) Setup blockPuller.AverageBlockSize = 200 bytes. Checkpoints are disabled, max MaxUnconsumedBlocksDataBytes = 1000. Avg block size is 500. 3 headers are presented, 2 are asked for download. 1 item is in the ToDownloadQueue. 
Make sure that expectedBlockDataBytes equals to 200*2. Make sure that hashes of 2 asked for download headers are inside expectedBlockSized list. Make sure that peer that was supplied was added to peersByPeerId.
3) 10 headers are presented, 10 are consumed by CHT (HeadersPresented returns the last header)
4) HeadersPresented called on 10 headers with triggerDownload == false. Make sure that BP wasn't asked for those blocks.
5) Setup blockPuller.AverageBlockSize = 200 bytes. MaxBlocksToAskFromPuller=100. Checkpoints are disabled. 200 headers are presented, 100 are asked for download. 5 was delivered. Nothing happens. 5 more deleivered- 10 asked from puller. 

====ProcessDownloadedBlock
1) Checkpoints are disabled. CT is at block 10. Block 11 is received. partialValidatior.StartValidation is called
2) Checkpoints are disabled. CT is at 9. Block data for 11 is received. partialValidatior.StartValidation is not called

====BlockDownloaded
1) Callback is registered with the hash of block X. Block data arrived for for an unknown header- nothing happens (callback not called). 
2) Callback is registered with the hash of block X. ExpectedBlockSIzes list initialized with block X. Block X data arrived with fake signature is presented- callback not called, peer is banned. Make sure that ExpectedBlockSizes is empty.
3) Callback is registered with the hash of block X. ExpectedBlockSIzes list initialized with block X. Block X data arrived and the block is mutated- callback not called, peer is banned. Make sure that ExpectedBlockSizes is empty.
4) Callback is registered with the hash of block X. ExpectedBlockSIzes list initialized with block X. Block X data arrived and the block's merkle tree root is not valid- callback not called, peer is banned.  Make sure that ExpectedBlockSizes is empty.
5) 2 callbacks are registered with the hash of block X. expectedBlockDataBytes is 1000,  expectedBlockSized list has hash of X with value of 100. Block X data arrived- callbacks are called, hash of presented block is removed from BlocksRequestd. Make sure expectedBlockDataBytes is equal to 900, expectedBlockSized contains no items.
6) 3 callbacks are registered for hashes X,Y. ExpectedBlockSIzes list initialized with blocks X,Y. BlockDownloaded is called on a hash of blocks X,Y with block=null. Callbacks are called with (null), hashes are removed from BlocksRequestd. Make sure that ExpectedBlockSizes is empty.

====GetOrDownloadBlocks
1) Setup blockPuller.AverageBlockSize = 200 bytes. GetOrDownloadBlocks called with 10 hashes. First two don't exist in CHT (uint256.One, uint256.Zero)- callbacks called with null. Next two exist and have block data assigned, this block data is not in BS (callback called with block data), 
next two have Block pointer as null, callback called with block data taken from block store (they exist there). Rest don't have block data anywhere and are marked for download (and make sure that BP is asked for those, BLocksRequested structure contains callbacks for each hash asked), make sure that entries in expectedBlockSized are created for them. Make sure ExpectedBlockDataBytes increased by 4 * 200.
2) GetOrDownloadBlocks called on a list of headers:  a1=a2=a3=a4=a7=a8=a9=b4=b6=b5=a10=a11=a12=a3=a4=a5=a6=a7. Make sure that block puller is asked for the following 7 jobs:
 a1=a2=a3=a4; a7=a8=a9; b4; b6; b5; a10=a11=a12; a5=a6;

====BlockMined
1) CT is at block 5. We mined new block on the top of block 4. Call BlockMined. CHT didnt create a new chained header for that block.
2) CT is at block 5. We mined new block on the top of block 5. Call BlockMined. CHT did create a new chained header for that block. Check that CT is 6.
3) CT is at block 5. We mined new block on the top of block 5. Block is invalid. Call BlockMined. CHT don't have a block for it in the tree. CT is at 5.

====OnPartialValidationCompletedCallbackAsync
1) Headers presented called with 1 new headers. OnPartialValidationCompletedCallbackAsync is called with PartialValidationResult.Succeeded == false and this block. Check that the peer that presented the header is banned. (this.peerBanning.BanAndDisconnectPeer was called).

====OnPartialValidationSucceededAsync
1) CT is at 5. OnPartialValidationSucceededAsync is called on 5b, CT is still at 5 (no reorg). Make sure that 5b.ValidationState == PV
2) CT is at 5. Peer 1 presents chain 4b,5b,6b. Peer 2 presents 4b,5c. Peer 3 presents 4b,5d,6d (doesn't provide data for 5d and 6d). Peer 1 and 2 provide data. We call OnPartialValidationSucceededAsync for 4b. It will start validation on 5b,5c (we have data for them) and for 5d validation won't be started. Mock the validator and make sure appropriate headers were asked for validation.
3) Setup blockPuller.AverageBlockSize = 200 bytes. CT is at 5. Headers for 6,7 are presented. Block data downloaded. OnPartialValidationSucceededAsync called on 6. Make sure we move CT to 6 (and validation state of 6 is FV) and start validation of 7. CHB mock had header 8 cached- we mark it for download (and CHT created it) and block puller was asked to download it after CT advancement.
4) CT is at 5, peer presents 6, simulate that data was provided and partially validated, 6 is invalid (full validation failed), peer is banned.

====FullyValidateLockedAsync
1) CT is at 5, we have headers for 5-10, block data for them (partially validated). FullyValidateLockedAsync called on 10. Make sure CT advance to 10. Block 5-10 were signaled, full validation was called on those blocks (full validator is mocked to always return true), make sure CHT consensus tip is at 10 and all marked FullyValidated.  FullyValidateLockedAsync return true;
2) CT is at 5. We get partially validated block 6. We call FullyValidateLockedAsync and it returns false; CT still at 5. 
3) CT is at 10. Another chain with fork point at 5 and total length of 15 is presented. Alt chain is partially validated, FullyValidateLockedAsync is called. Block number 9 is invalid. Make sure that CT returns to the original chain. Nothing was signaled.
4) Setup blockPuller.AverageBlockSize = 200 bytes. CT is at 100. We advance to 600. Make sure that finalized block height is at 100. Reorg towards a shorter chain with more chainwork so the total chain length is 550. Make sure that finalized block height is still at 100. Make sure ProcessDownloadQueueLocked is called (mock BP, add some headers to the queue, make sure BP was requested to download them). 
5) Block store is disabled. A claims chain with tip 100a. We are at 120a and have a reorg to 150b (presented by peer 2, fork point at 100a) and we don't have block data for 0a-110a. Reorg fails because block b110 is inavalid. Make sure CT is at the forkpoint 100a. (test is done under assumption that coinview can be rewinded with 1 block granularity). Make sure that after that all headers after CT are removed and CT.Next have no elements. Make sure all peers are removed from the peersByPeerId data structure.
6) Block store is disabled. A claims chain with tip 100a. We are at 120a and have a reorg to 150b (presented by peer 2, fork point at 100a). When we rewind we end up at block 90a. We don't have block data for 0a-95a. Reorg fails. Make sure CT is at the 90a. Make sure that after that all headers after CT are removed and CT.Next have no elements. Make sure all peers are removed from the peersByPeerId data structure.
7) Block store is disabled. A claims chain with tip 100a. We are at 120a and have a reorg to 150b (presented by peer 2, fork point at 100a). When we rewind we end up at block 100a. We connect new chain and fail at 110b because it's invalid. Then we rewind till 90a. We don't have block data for 0a-95a. Make sure CT is at the 90a. Make sure that after that all headers after CT are removed and CT.Next have no elements. Make sure all peers are removed from the peersByPeerId data structure.
8) Block store queue is enabled and mocked. A claims chain with tip 100a. We are at 120a and have a reorg to 150b (presented by peer 2, fork point at 100a) and we don't have block data for 0a-110a in the CHT. Reorg fails because block b110 is inavalid. Make sure that block store was asked to provide blocks 101a-110a (only those). Make sure CT is 120a.
9) Peer 1 presents chain to 600a. Peer 2 presents a chain with FP at 50a that goes to 599b. We advance on chain A till the block 550 and when we advance to 551 peers to resync will contain peer 2 ID. (for this test mock finalizedBlockHeight so it implements the correct behavior but avoids the database usage). 

====MIXED TESTS
1) CT is at 5. Header 6 is presented. Header 6 is disconnected. Partial validation started on header 6. Partial validation finished and succeeded. Make sure CT didn't advance.
2) CT is at 5. Alt chain with fork at 4 is presented. That chain is 7 headers long. 5b is disconnected. Header 5b is partially validated and succeeded. Make sure partial validation wasn't called on 6b.
3) CT is at 5. Header 6 is presented. Header 6 is disconnected. Partial validation started on header 6. Partial validation finished and failed. No peer banning was called.


___TODO
Write several tests when we initialize and block store, chain repository and coinview are at different height. Test every case
when they are on forks and when each of the components is ahead of every other one and so on. All combinations.

add test that will supply invalid headers (and check if we have one already)

add tests for when we mark block hashes invalid (also make sure that in case of 2 exceptions we don't ban the block hash forever.) Those  exception are: 
	BadWitnessNonceSize - don't ban at all
	if RejectUntil is set- ban for the time specified there
also make sure that when header is presented with hash of a block that was previously banned we discard such a header and fail header validation.

add tests bock signaling one by one when we connect a new chain and when we rewind. Check that the consensus tip is set at every midstate

check this issue: https://github.com/stratisproject/StratisBitcoinFullNode/issues/2015 scenario is covered. Reproduce the scenario and make sure node can handle it.

remove all the tests that test GAP situation

add tests for IsAtBestChainTip

Another test modification should be integrity being the out of the lock

Test cases when peer delivers mutated block. Make sure block assigned back to the puller ignoring normal queue in CM. It should be delivered by other peer eventually

Test that tests that CM would add witness services requirment in case validation failed with BadWitnessNonceSize error.

5 blocks downloaded, first one is PV but FV invalid. Make sure PV doesnt start on the next block

**Comment by fassadlr** [comment]
These tests has been implemented. If more test coverage is required please raise another issue.
