### ISSUE TITLE
Failing integration unit tests - cannot access the file '_DBreezeSchema'

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/StratisBitcoinFullNode#232]
I'm running Windows 7 and running the integration unit tests using the VS2017 test runner. The following unit tests fail:

BlockStoreCanRecoverOnStartup()
WalletCanRecoverOnStartup()

Both fail with the following error: Message: System.IO.IOException : The process cannot access the file '_DBreezeSchema' because it is being used by another process

**Comment by Aprogiena** [comment]
I do receive those as well lately.

**Comment by Aprogiena** [comment]
I've noticed that many tests fails for me from time to time because of a similar problem - they try to clean TestData directory and they can't. And there is dotnet.exe process that holds handles to that, so if that is killed, those tests work again. 

I'm not sure why that process is there, but seems to be like instance of a previous tests or something that is not cleaned up properly.

**Comment by mikedennis** [comment]
After further testing I'm almost 100% sure that these failures for me were also due to orphan dotnet.exe processes. With clean boot can run all tests through VS2017 test runner successfully.

**Comment by Aprogiena** [comment]
@mikedennis the question is whether this is caused by our code or by VS2017; if it is by our code, it is a bug and should be fixed
