### ISSUE TITLE
[Mempool] CheckSigOps using incorrect constant

### ISSUE THREAD

**Issue by zeptin** [stratisproject/StratisBitcoinFullNode#2470]
Used in https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin.Features.MemoryPool/MempoolValidator.cs#L768 ->

`if (context.SigOpsCost > this.ConsensusOptions.MaxBlockSigopsCost)`

Used in core https://github.com/bitcoin/bitcoin/blob/master/src/validation.cpp#L724 -> 

`if (nSigOpsCost > MAX_STANDARD_TX_SIGOPS_COST)`

These are two distinct constants with their own values (the max for blocks is 80 000 and the max for a single transaction is 80 000 / 5 = 16 000).

**Comment by majikandy** [comment]
I experienced a bug partly because of this with a new network.....  I can get a transaction into the mempool where its sig ops is 2.  (well below the 20,000 max which stratis has)....  and you are right, this should be 1/5 of the 20,000 really

Yet this can never get mined because it has many ancestors..... and at consensus time it does the check of the transaction sigops and the sigops of all its ancestors which comes to 56835, well above the max sig ops for a transaction and even a block.

It seems the calculation for ancestors is done after the sig ops check at mempool time but it is done before at consensus time...

**Comment by majikandy** [comment]
I notice this in the config which could possibly overcome it ? 

#Maximal size in kB of ancestors of a transaction in mempool (including itself). Defaults to 101kb.   That transaction is actually 113kb in the mempool.

**Comment by dangershony** [comment]
We should fix trx builder, miner and mempool.

**Comment by MithrilMan** [comment]
some references about this subject:
https://gist.github.com/gavinandresen/4135d03a56e0ecd146c7
https://github.com/bitcoin/bitcoin/issues/747
https://github.com/bitcoin/bitcoin/pull/4150

**Comment by MithrilMan** [comment]
I'm working on this issue, this is the branch if you want to check it before PR
https://github.com/stratisproject/StratisBitcoinFullNode/compare/master...MithrilMan:bug/maxStandardTxSigopsCost?expand=1

**Comment by MithrilMan** [comment]
@dangershony I'm not sure we need to fix builder/miner/mempool if the problem was just that we were accepting a nonstandard transaction in memory pool.
AFAIU the other checks were against the right parameter, in bitcoincore we find only two occurrances of MAX_STANDARD_TX_SIGOPS_COST`
https://github.com/bitcoin/bitcoin/search?utf8=%E2%9C%93&q=MAX_STANDARD_TX_SIGOPS_COST&type=

Can somebody confirm that my changes are enough?
https://github.com/stratisproject/StratisBitcoinFullNode/compare/master...MithrilMan:bug/maxStandardTxSigopsCost?expand=1

**Comment by majikandy** [comment]
suggest reopening as the PR only covers part of the problem
