### ISSUE TITLE
[PH] store stake info in memory for forward looking headers

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#2500]
This line is problematic in PH rule validation 
https://github.com/stratisproject/StratisBitcoinFullNode/pull/2381/files#diff-c0bed2cb85d3ca47e2fb7a8c5c5e12e8R220

*Problem:*
We ask for stake info (to get the stake modifier) from StakeStore but that will only calculate stake info up to current CT.

*The solution:*
At that point of validation we have all required info to calculate stake modifier for current PH so we calculate it and store it in the PH header (it will not get serialized to disk, or should it? see bellow)
After verifuing stake modifier and kernal is correct we will calculate the stake modifier for current block using `stakeValidator.ComputeStakeModifierV2()`

**Comment by dangershony** [comment]
*One more option:*

Storing stake modifier in PH header AND passing it in payloads and storing it to disk.
- Benefit: this will reduce the complexity of the code 
- Downside: Increase the amount of data we store to disk (but only slightly)

I suggest we consider putting stake modifier in PH as a serialised citizen.

**Comment by noescape00** [comment]
In order to validate PH we need to validate coisntake kernel which is inside of PH. This validation requires information from the stake chain, more specifically - stake modifier. 
Usually we get this from StakeStore but stake store only has this info for blocks that are already part of consensus chain. Now we need this info after consensus tip to validate proven headers. 

Therefore we need a way to access this information. 
I think we can implement it by adding a field to PH (it will not be serialized and saved to disk\sent to network\ affect hash)- this field will contain stake modifier. 

When we need to validate PH N we will go to PH N-1 and get modifier from there. 
After that we will be able to calculate modifier for N and then we should save it in N's modifier field.

**Comment by MithrilMan** [comment]
To compute stakeModifier from previous header, I need that the previous header exposes that information.
Are we sure that if we validate a header after last checkpoint, the previous header is a ProvenHeader ?
Since we allow whitelisted stratisX peers to return us legacy headers, we can't ensure this is true, so the `StackModifier` property should be added to `PosBlockHeader` and not to `ProvenBlockHeader` and that property should be computed for both normal PoS headers and PH headers. Is this right? How we approach this?
@noescape00 @dangershony

**Comment by noescape00** [comment]
>Are we sure that if we validate a header after last checkpoint, the previous header is a ProvenHeader ?

no. we might as well be syncing from whitelisted qt node- in that case we don't have proven header there

>Since we allow whitelisted stratisX peers to return us legacy headers, we can't ensure this is true

Yes

>StackModifier property should be added to PosBlockHeader and not to ProvenBlockHeader and that property should be computed for both normal PoS headers and PH headers. Is this right? How we approach this?

Hmm. Probably not. 
But that would mean that before we download blocks from qt we can't validate proven headers because we won't have stake modifier. 
But adding it to pos header sounds extremely hacky. 

So I'm not sure how to do it nicely in terms of design. 
@dangershony any thoughts?

**Comment by MithrilMan** [comment]
Maybe I've a solution, or 2.
1) If we consider what rised this task (the lack of a BlockStore in StakeChain) we could solve the problem implementing a proxy StakeChain layer that can access BlockStake from this (if exists) or from memory (actually missing, so a sort of Cache implementation of IStakeChain).
We can then put in that cache the BlockStake computed just by the header (is this technically possible or are we missing information? In case we can populate what we have and create a flag to signal that BlockStake is partial created so we can then fill it with missing information once we have a Block and we can store it on disk)
Having all the BlockStake there, allow us to rely on the BlockStakeProxy to obtain the value we need (StackModifierV2) to validate headers.

2) Solution number 2 is quite an architecture hack: actually we want to allow whitelisted peers to sync with legacy header.... what if we implemet this as a custom network rule, leaving this out from standard c# full node, and just create some kind of FullNode proxy that skip the PHvalidation part and just talk to those whitelisted nodes? This way we can use this special kind of nodes to sync from StratisX like they do now, but other FullNodes can't and will just sync with Proven Headers (once activated).

I will elaborate on a call if needed

**Comment by MithrilMan** [comment]
needed re-design, addressed in https://github.com/stratisproject/StratisBitcoinFullNode/issues/2662.
