### ISSUE TITLE
StratisX is slow to sync up from C# node

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2570]
When new installation of StratisX is syncing from fully synced SBFN StratisX will be able to download upto 500 blocks at a time.
It would appear that whenever a new block is staked on the network StratisX will be able to download another 500 blocks.
It is also possible to restart StratisX to force syncing of 500 blocks.

**Steps to reproduce**
 - Start SBFN and fully synchronise the node with the network
 - Start StratisX making sure to use empty data directory and a single connection to SBFN node `-connect=<SBFN node IP address>:<port>`
 - Observe slow syncing of StratisX node in increments of 500

**Comment by maciejzaleski** [comment]
This has been confirmed by @ArcSin2000X to be a problem on the Mainnet as well.

**Comment by bokobza** [comment]
I can confirm that this doesn't happen when the X node is started and only connect to another X node.

**Comment by zeptin** [comment]
As discussed with Maciej earlier, I am not sure why X is so slow to sync, but it does not get stuck for me:

```
received: block (176 bytes)
received block e184b52d611c01d0efdd18cd99c65654a6c40cd524042c58024a89e15f27ef5d
GetStakeEntropyBit: hashBlock=e184b52d611c01d0efdd18cd99c65654a6c40cd524042c58024a89e15f27ef5d nEntropyBit=1
ComputeNextStakeModifier: prev modifier=0x22d9ea85e47cf31b time=2017-05-25 01:50:56 UTC
SetBestChain: new best=e184b52d611c01d0efdd18cd99c65654a6c40cd524042c58024a89e15f27ef5d  height=500  trust=254344562352446642  blocktrust=1380111  date=05/25/17 01:53:53
ProcessBlock: ACCEPTED
No valid UPnP IGDs found
upnp thread exit
received: inv (37 bytes)
  got inventory: block 5fac68b79a129fcf92f2c4df29af4fcaafb5ce5bb9798acf646d69df8bb370f2  new
askfor block 5fac68b79a129fcf92f2c4df29af4fcaafb5ce5bb9798acf646d69df8bb370f2   0 (00:00:00)
sending getdata: block 5fac68b79a129fcf92f2c4df29af4fcaafb5ce5bb9798acf646d69df8bb370f2
sending: getdata (37 bytes)
received: block (401 bytes)
received block 5fac68b79a129fcf92f2c4df29af4fcaafb5ce5bb9798acf646d69df8bb370f2
ProcessBlock: ORPHAN BLOCK 0, prev=5a800875f36caed434d2c884e4968bb677cc1c2bd117f2d444f16221f817ff7e
sending: getblocks (677 bytes)
received: inv (18003 bytes)
```

The above is the tail end of the first 500 blocks on testnet getting downloaded by X from its only connection, an SBFN node.

The logic is that the peer supplying the blocks keeps track of the hash of the last block. When it receives a `getdata` for it, it 

In this case `e184` is the last block of the first 500 blocks downloaded.

So when SBFN is asked for it by X it sends the 37 byte `inv` with its chain tip hash.
In this case block `5fac` is height 624635. `e184` is block 500. X then requests this block via `getdata`.
Once downloaded, X realises it is an orphan block and sends another `getblocks` with a fresh locator as you can see from the log, and receives an `inv` from SBFN of the next 500 headers.

This logic seems to be functioning correctly in my opinion. I do not see the reported behaviour of the download ceasing completely after the first 500 blocks. After the log extract above the X node proceeds to download each of the next 500 blocks in turn. I let it download up to ~16000 blocks before stopping the test.

**Comment by kogot** [comment]
Logic you described I can see in a code but after first 500 blocks SBFN does not send invContinue message,
because at that point :  if (item.Hash == this.getBlocksBatchLastItemHash)  (BlockStoreBehavior.cs), this.getBlocksBatchLastItemHash is null. And it's Null because here https://github.com/stratisproject/StratisBitcoinFullNode/blob/c26721a7f075958e2da20929983c32853ad172d9/src/Stratis.Bitcoin.Features.BlockStore/BlockStoreBehavior.cs#L267

this.consensusManagerBehavior.BestSentHeader is NULL.

Happens on my box all the time

**Comment by zeptin** [comment]
I see what you mean, although in my case it did not happen for some reason.

With that in mind, the cause is pretty simple - X does not send `getheaders` (although it can receive and process them). Instead it sends `getblocks`. The `getblocks` handler in the block store behaviour does not set the `BestSentHeader` property in the consensus manager behaviour. This is different to the `getheaders` handler, which does. This seems like it should be an easy fix.

**Comment by zeptin** [comment]
To be more specific, `UpdateBestSentHeader()` only gets called inside that `if`. So we need to call it somewhere earlier in `ProcessGetBlocksAsync()` if the last sent header is `null`. Perhaps if we set it to genesis, or to the highest known height of the peer (perhaps using its locator).

**Comment by bokobza** [comment]
yeah that's the fix @kogot , I'm testing a fix now.

**Comment by maciejzaleski** [comment]
Retested on Testnet with @bokobza and on Mainnet. The node is able to fully synchronise.
