### ISSUE TITLE
SBFN node is failing to keep up with StratisX

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/StratisBitcoinFullNode#2579]
**Setup**
StratisX and SBFN are occasionally able to sync to the same block height.
Most of the time SBFN will be about 10 blocks behind StratisX and when SBFN falls 10-20 blocks behind StratisX SBFN will synchronise to the latest block height.

**Steps to reproduce**
 - Start SBFN node which is connected only to StratisX node
 - Start StratisX node which is connected to the network
 - Observe slow block height update (SBFN will be usually 10-20 blocks behind StratisX)

**Comment by maciejzaleski** [comment]
Logs from two nodes described in this issue:
[2570.zip](https://github.com/stratisproject/StratisBitcoinFullNode/files/2505754/2570.zip)

**Comment by ArcSin2000X** [comment]
I have now tested this scenario on mainnet and I can see SBFN node is constantly running 6 blocks behind StratisX

**Comment by zeptin** [comment]
I think I've found a possible reason for this, just running some additional analysis to be sure. It appears X initially announces blocks via unsolicited `inv` payloads, which we do not handle anywhere in the behaviours.

X generates block (done here via RPC `generate`, not sure if that makes a difference to the announcement logic):

```
CheckWork() : new proof-of-work block found  
  proof hash: 35a63154068506d2b52c7d34f2c22c17b1bddf76257c6a099b8db28e5b5f3df8  
target: 7fffff0000000000000000000000000000000000000000000000000000000000
CBlock(hash=d97d56067438b18588d48e97d5cde6a2a11bc1e2bee37a28ff7cc4ab74c81c1d, ver=7, hashPrevBlock=56e3c1b83edd9828a066c4ce73d4b8235f3bc635202419eb234b74cec9fb9c99, hashMerkleRoot=10586fad010d3122ceb9fd23f04b6b223e308e780f919419c5f27d08b1341122, nTime=1540432088, nBits=207fffff, nNonce=0, vtx=1, vchBlockSig=)
  Coinbase(hash=10586fad010d3122ceb9fd23f04b6b223e308e780f919419c5f27d08b1341122, nTime=1540432088, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 570101)
    CTxOut(nValue=4.00, scriptPubKey=OP_DUP OP_HASH160 fbb661f9935356673de8588b49b9d080eb412e6a OP_EQUALVERIFY OP_CHECKSIG)

  vMerkleTree:  10586fad010d3122ceb9fd23f04b6b223e308e780f919419c5f27d08b1341122

generated 4.00
keypool keep 8
AddToWallet 10586fad010d3122ceb9fd23f04b6b223e308e780f919419c5f27d08b1341122  new
SetBestChain: new best=d97d56067438b18588d48e97d5cde6a2a11bc1e2bee37a28ff7cc4ab74c81c1d  height=7  trust=16  blocktrust=2  date=10/25/18 01:48:08
ProcessBlock: ACCEPTED
```

I then see an `inv` message get sent from X to SBFN (`inv` in hex is 69 6E 76):

```
 6C EA 8F 00 00 00 13 00 00 00 7F 00 00 01 7F 00
 00 01 06 00 00 00 00 00 00 00 00 51 00
 6C EA 8F 00 00 00 14 00 00 00 46 51 C0 6D 38 2E
 6C 58 BB 91 48 12 50 18 08 02 00 00 00 00
 6C EA 8F 00 00 00 3D 00 00 00 CD F2 C0 EF 69 6E
 76 00 00 00 00 00 00 00 00 00 25 00 00 00 5E 1E
 7D 92 01 02 00 00 00 1D 1C C8 74 AB C4 7C FF 28
 7A E3 BE E2 C1 1B A1 A2 E6 CD D5 97 8E D4 88 85
 B1 38 74 06 56 7D D9
```

In my packet captures SBFN responds to these with empty `getdata` requests, but I don't know whether that is some sort of fall-through case or not (`getdata` = 67 65 74 64 61 74 61):

```
 6C EA 91 00 00 00 13 00 00 00 7F 00 00 01 7F 00
 00 01 06 00 00 00 00 00 00 00 00 2D 00
 6C EA 91 00 00 00 14 00 00 00 C0 6D 46 51 BB 91
 48 12 38 2E 6C 95 50 18 98 8F 00 00 00 00
 6C EA 91 00 00 00 19 00 00 00 CD F2 C0 EF 67 65
 74 64 61 74 61 00 00 00 00 00 01 00 00 00 14 06
 E0 58 00
```

The `00` following `getdata` is the number of entries, i.e. an empty request.

So what happens now is nothing. X ignores the spurious `getdata`, and SBFN does not get the block because it doesn't know to ask for it.

Eventually SBFN sends a `getheaders` as part of its normal operation. This causes X to respond with a `headers` payload, which SBFN does know how to handle. Then it syncs.

In my test the `getheaders` was sent almost 2 minutes after the block was generated, but the `getheaders` may just get sent periodically via an unrelated timer, or after a `ping`/`pong` interaction, so I wouldn't pay too much attention to that duration. The important thing is the lack of `inv` handling.

X source code reference for `inv` handling: `main.cpp` function `ProcessMessage`.

X source code reference for `inv` announcement of new blocks: `main.cpp` function `AcceptBlock`:
```
    // Relay inventory, but don't relay old inventory during initial block download
    int nBlockEstimate = Checkpoints::GetTotalBlocksEstimate();
    if (hashBestChain == hash)
    {
        LOCK(cs_vNodes);
        BOOST_FOREACH(CNode* pnode, vNodes)
            if (nBestHeight > (pnode->nStartingHeight != -1 ? pnode->nStartingHeight - 2000 : nBlockEstimate))
                pnode->PushInventory(CInv(MSG_BLOCK, hash));
    }
```

**Comment by maciejzaleski** [comment]
The PR #2611 has fixed the problem.
