### ISSUE TITLE
Transaction.Parse differs from original NBitcoin implementation

### ISSUE THREAD

**Issue by babgev** [stratisproject/StratisBitcoinFullNode#3218]
With [this commit](https://github.com/MetacoSA/NBitcoin/commit/6337398058c97b69100ca8d00ba65f124aa49780#diff-c7bf4fe7822a4cd50792b3db0116a683) NBitcoin's implementation of transaction parsing is different. 
I can implement the changes and send a PR.

**Comment by bokobza** [comment]
@babgev the link doesn't work here, can you please double-check?
Thanks

**Comment by babgev** [comment]
> 
> 
> @babgev the link doesn't work here, can you please double-check?
> Thanks

Sorry, I just fixed it.

**Comment by bokobza** [comment]
so we're not actually using Transaction.Parse in our code and the way to create a transaction is to use `Transaction trx = this.network.Consensus.ConsensusFactory.CreateTransaction(hex);`

@fassadlr is that correct?

**Comment by fassadlr** [comment]
@bokobza Yes that is correct. @babgev should the dev wish to create a transaction is has to be done via the network. I.e. the network is responsible creating the transaction. This is because Stratis has different network types depending on if it is Proof of Work, Proof of Stake or Proof of Authority.

A shorter way to create a transaction can be expressed like so:

`Transaction trx = this.network.CreateTransaction(hex);`

**Comment by babgev** [comment]
@fassadlr thanks, I used that.
I just thought that you are aiming to have the same API as NBitcoin.

**Comment by fassadlr** [comment]
@babgev I believe we were, in the past, but now we are only following what's relevant to us in our codebase.

**Comment by bokobza** [comment]
Thanks @fassadlr and thank you @babgev for the feedback. Any other questions, please ask 😃

**Comment by babgev** [comment]
Cool thank you guys.
