### ISSUE TITLE
[SideProject] aspnet core browser wallet

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#363]
A feature that will greatly improve our node.   
The plan is to add a feature that will have asp.net web pages that can act as a browser wallet.
The feature will simply start a self host server (like our api or RPC) and serve a web page on a specific local port.   
The WebsiteFeature feature will just show simple stats page (i.e. current chain height, connected nodes etc...) then other feature will be able to implement their own controllers with specific info (wallet can show the users balance etc...)

```
    var node = new FullNodeBuilder()
                .UseNodeSettings(nodeSettings)
                .UseConsensus()
                .UseBlockStore()
                .UseMempool()
                .AddMining()
                .AddRPC()
        ->      .AddDashboard()
                .Build();
```

Probably the simplest design to start is razor pages.

**Comment by noescape00** [comment]
Not sure if we can do it this way. 
I've tried to add a new feature project with .net core mvc website and run it from Stratis.StratisD project but it just wont publish (won't run on IIS on my PC).

I've created a [question on StackOverflow](https://stackoverflow.com/questions/47576151/running-asp-net-core-web-app-from-net-core-console-app?noredirect=1#comment82203071_47576151) an it looks like some people tried to achieve that but failed. So now there is a 50 reputation points bounty for the next 6 days, hope someone will figure it out.

**Comment by MithrilMan** [comment]
as i told, i'm working on an angular5 template for that, the skeleton is already working, now let's talk about integrating custom modules into the dashboard.

I don't know if you want to consider stratis as a core feature, in this scenario we could add Interfaces and Attributes in the Stratis core library so that anyone creating a feature can use them to export widget.
The other way is to create a separate library, something as Stratis.Dashboard.Core, that have those interfaces and attributes. So depending on the feature, who wants to export data to the dashboard can reference that library.

In any case, the dashboard could then check for any implementation of its interface or attribute, and then register those extension and expose them

so basically the library could have some interface like

```interface IDashboardAction {
   string ActionName { get; }
   List<DashboardParameterType> Parameters { get; }
   bool  Execute()
}```

and than having a class that implements that interface, in a custom feature

meanwhile the dashboard feature will go through all the loaded assembly (or querying all registered features) to see any class that implements that interface, and register it and then expose on the dashboard page

I don't know if i gave an idea, it's more complex than how i described it, probably it's better if i try to implement an example

**Comment by dangershony** [comment]
This is how I would envisage this.
We have an Interface in base feature that can register linkes to a features web pages (UI) and each feature that wants to expose a web page will have a controller (and views) and use the interface to register its controller endpoints.

We will then have a base web feature (similar to api feature or maybe merge the two) that will start a web server and serve pages, the default will the basic stuff of the node (last blocks headers, connected nodes) then feature will be able to add their own web pages 
- mempool will show items in pool 
- store will show last blocks etc
- wallet can show history, current receive address etc... 
- miner feature can enable the staking

Wallet will not send as that requires the password, instead @bokobza proposed we write a chrome plugin for sending from the wallet.

That will give us a dynamic UI where a feature can just create its own UI pages.

**Comment by MithrilMan** [comment]
The problem about injecting views into the dashboard is that you can be open to security issues, where a feature inject scripts that act as backdoors or vulnerabilities

If this isn't an issue for you, then ok but users who will use 3rd party features and just plug them into their nodes, must be aware of the risk.

Anyway I'll think about how to accomplish to your vision

P.S.
when you say "We have an Interface in base feature that can register linkes to a features web pages" do you mean that actually that interface alrady exists?

**Comment by dangershony** [comment]
I think the vulnerabilities is not a big issue as long as we dont allow to share the wallet password in a dashboard page.

The interface does no exist yet no, you need to create it ;)

**Comment by dangershony** [comment]
Closing issue as its now moved to the SDF
