### ISSUE TITLE
Block Store race condition

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#599]
The block store will sometimes fall behind.

Because of this code in consensus
```
                this.chainState.HighestValidatedPoW = this.Tip;
                if (this.Chain.Tip.HashBlock == item.ChainedBlock?.HashBlock)
                    this.FlushAsync().GetAwaiter().GetResult();

                this.signals.SignalBlock(item.Block);
```

The problem is store uses this condition to store a block
```
                if (this.StoreTip.Height >= this.ChainState.HighestValidatedPoW?.Height)
                    break;
```

A very rare race condition can happen where `HighestValidatedPoW` is updated and store is trying to look for the next block in pending storage collection but `signals.SignalBlock` did not push the block yet to that collection.

Then the node will try to download the block.

**Comment by noescape00** [comment]
Code that this issue is referring to is no longer in the repository. Was this issue resolved?

**Comment by dangershony** [comment]
I believe this is still an issue as this applies to the store persistence and not relay part of the block Signaler.

**Comment by noescape00** [comment]
@dangershony after investigating this one for a while I came to a conclusion that StoreBlockPuller and loopsteps related to it are redundant. Basically the only thing that BlockStore does is getting a block from signaler, reorging the repo if needed and saving blocks to the repository. And every time it actually downloads a block (once in a few thousands if we're lucky to catch it)- it's a wrong download and this block was already downloaded by the LookaheadBlockPuller which is the only block puller that does all the downloading (even though in summary it is said that LookaheadBlockPuller is used only for IBD but actually it is used always. And it's used for the light node where we can't use block store). 

The only blocks that are being downloaded by StoreBlockPuller are ones that has been already downloaded (2nd downloads caused by that race condition). 

So if we remove those unused steps we can get rid of the race condition, occasional high CPU usage (discussed in PR 1125) and make code more simple.
I'll test this thoroughly.

**Comment by dangershony** [comment]
Based on PR #1132 we still need to fix the small CPU boost even on the current code base.
