### ISSUE TITLE
Create Thread Safety Best Practices Guideline

### ISSUE THREAD

**Issue by nopara73** [stratisproject/StratisBitcoinFullNode#617]
I am trying to get my head around proper locking practices, this topic deserves a nice long discussion and it would be beneficial if we could all come to the same line here. @Neurosploit @Aprogiena @dangershony @bokobza  
@NicolasDorier, @wintercooled you might be interested in this, too.  

# lock
We started out having the plain old familiar `lock`. It's usage is straightforward, it works well.  

```cs
int[] myArray;
object myArrayLock = new object();

public IEnumerable<int> FindBiggerThan(int number)
{
    lock(myArrayLock)
    {
        return myArray.Where(x => x > number).ToArray();
    }
}
```

# SemaphoreSlim, AsyncLock  

With the introduction of async in .NET locking became more complicated. You cannot await inside a lock. For one, .NET introduced an async semaphore: `SemaphoreSlim`:  

```cs
int[] myArray;
SemaphoreSlim semaphoreSlim = new SemaphoreSlim(1, 1);
public async Task<IEnumerable<int>> FindBiggerThanAsync(int number)
{
    await semaphoreSlim.WaitAsync();
    try
    {
        await Task.Delay(100);
        return myArray.Where(x => x > number).ToArray();
    }
    finally
    {
        semaphoreSlim.Release();
    }
}
```

This works great, too, however
1. `SemaphoreSlim` must be disposed, so the class it lives inside must either make sure it'll be disposed or implement `IDisposable` interface and delegate the disposing to the class that's using the class.  
2. The plain old locking is just more readable.  

So why not implement an async lock to solve the second problem instead? Turns out Stephen Cleary and Stephen Toub both have their own independent implementations of this and their implementations solve both problems with `SemaphoreSlim`. For reference see [Creary's here](https://github.com/StephenCleary/AsyncEx/blob/master/src/Nito.AsyncEx.Coordination/AsyncLock.cs) and [Toub's here](https://www.hanselman.com/blog/ComparingTwoTechniquesInNETAsynchronousCoordinationPrimitives.aspx).  
For my example I'll use Toubs:  

```cs
int[] myArray;
AsyncLock myArrayLock = new AsyncLock();
public async Task<IEnumerable<int>> FindBiggerThanAsync(int number)
{
    using (await myArrayLock.LockAsync())
    { 
        await Task.Delay(100);
        return myArray.Where(x => x > number).ToArray();
    }
}
```

# Concurrent Collections

We might can even remove the locks altogether and just use concurrent collections, like `ConcurrentDictionary`. 

```cs
ConcurrentDictionary<int, int> myDic;

public async Task<IEnumerable<int>> FindBiggerThanAsync(int number)
{
    await Task.Delay(100);
    return myDic.Where(x => x.Value > number).Select(x => x.Value).ToArray();
}
```

[Jon Skeet says](https://stackoverflow.com/a/17776463/2061103):  

> If elements are added or removed after you start iterating, they may or may not be included in the iteration.  

This sounds great, however [not all threading issues can be ignored](https://stackoverflow.com/questions/1949131/net-dictionary-locking-vs-concurrentdictionary).  

> A threadsafe collection does not, however, guarantee that sequential operations on the thread all work on the same "snapshot" of its internal data structure  
  
> For example, if you first check if a key exists and then later get the value that corresponds to the key, that key may no longer exist

Furthermore we don't always have a concurrent collection we want to use. We might want to use arrays, because of its performance. And indeed in Bitcoin we often iterate through many transactions and keys, so we need high performance.  

To sum up: we still need to use locks, because,  
1) not all threading issues can be ignored,  
2) we need performance.  

# ReaderWriterLockSlim, AsyncReaderWriterLockSlim

But hey, speaking of performance. It doesn't matter if a bunch of thread reading a collection the same time, what matters is: don't read it when you also write it. This is where `ReaderWriterLockSlim` comes in.

```cs
int[] myArray;
ReaderWriterLockSlim myArrayLock = new ReaderWriterLockSlim();

public IEnumerable<int> FindBiggerThan(int number)
{
    myArrayLock.EnterReadLock();
    try
    {
        return myArray.Where(x => x > number).ToArray();
    }
    finally
    {
        myArrayLock.ExitReadLock();
    }
}

public void Modify(int index, int value)
{
    myArrayLock.EnterWriteLock();
    try
    {
        myArray[index] = value;
    }
    finally
    {
        myArrayLock.ExitWriteLock();
    }
}

// even better, if we're not sure if we'll modify or write
public bool TryUpdate(int index, int value)
{
    myArrayLock.EnterUpgradeableReadLock();
    try
    {
        if(myArray[index] != value)
        {
            myArrayLock.EnterWriteLock();
            try
            {
                myArray[index] = value;
                return true;
            }
            finally
            {
                myArrayLock.ExitWriteLock();
            }
        }
        return false;
    }
    finally
    {
        myArrayLock.ExitUpgradeableReadLock();
    }
}
```

Of course we need an async way to do this, too. Both [Stephen Cleary and Stephen Toub have their own implementations](https://stackoverflow.com/a/19664437/2061103).  

However this has the same two problem as with `SemaphoreSlim`:  

1. `ReaderWriterLockSlim` and `AsyncReaderWriterLockSlim` must be disposed, so the class it lives inside must either make sure it'll be disposed or implement `IDisposable` interface and delegate the disposing to the class that's using the class.  
2. The plain old locking is just more readable.  

# IEnumerable and yield return

Speaking of performance again, we often will want to stream our collections instead of `ToArray` it midway. This is called deferred execution.  
Remember I put a `ToArra()` in my first example?  I did it, because without it, it's actually [not thread safe](https://stackoverflow.com/a/9096487/2061103):  

```cs
int[] myArray;
object myArrayLock = new object();

public IEnumerable<int> FindBiggerThan(int number)
{
    lock(myArrayLock)
    {
        return myArray.Where(x => x > number);
    }
}
```

If we'd use a concurrent collection, then it'd be thread safe, but again: that's less performant than an array.

Maybe it's better to (1) either use a concurrent collection or (2) delegate thread safety to the caller?  

# Thread-Safe Enumeration

There's a [Codeproject article](https://www.codeproject.com/Articles/56575/Thread-safe-enumeration-in-C) with 5 stars and 31 upvotes about it. He implements a `SafeEnumerator`, a `SafeEnumerable` classes and `IEnumerable<T> AsLocked` extension, those let's you do some neat stuff, like this one:  

```cs
int[] myArray;
object myArrayLock = new object();

public IEnumerable<int> FindBiggerThan(int number)
{
    return myArray.Where(x => x > number).AsLocked(myArrayLock);
}
```

Or simply delegate locking to the caller:

```cs
foreach(var number in FindBiggerThan(2).AsLocked(myArrayLock))
{
    Console.WriteLine(number);
}
```

In fact if, you use the same `myArrayLock` lock in both places, it'll not deadlock.  
It works, because, as he says:  
> A great thing about `foreach` (and, by extension, LINQ) is that it correctly executes the `Dispose()` method of the enumerator. That is, `foreach` actually becomes a `try`-`finally` statement, where the enumerator is created, then iterated inside a try block, and disposed in `finally`.

An additional consideration with this approach:  
> While it's all good when using foreach, using this enumerator by explicitly calling collection.GetEnumerator() is more dangerous than before. Forget to call Dispose() on it, and your collection is stuck in a lock forever. Implementing the finalization pattern on the enumerator might help with it, but really, the way to go is to never use GetEnumerator() unless absolutely necessary. And really, don't use it even then.  

Plus he notes the `ReaderWriterLockSlim` works with it.  
> Another possible upgrade to the thread-safe enumerator is using ReaderWriterLockSlim in place of Monitor. As iterations do not change the collection, it makes sense to allow many concurrent iterations at once, and only block concurrent changes to the collection.  

# Ending Thoughts

I think it'd be highly beneficial to create some locking best practices. Hopefully this thread will generate some conversation and I or someone will propose some guidelines based on it.

**Comment by nopara73** [comment]
Here's the Best Practices Guide I'd use based on my current knowledge:  

# Level 0: Maximum Thread Safety And Code Simplicity  
- Use concurrent collections,
- use `lock` and `AsyncLock`,
- avoid deferred execution.  

# Level 1: Better Performance
- Drop `lock` and `AsyncLock`, 
- use `ReaderWriterLockSlim` and `AsyncReaderWriterLockSlim`.

# Level 2: Good Performance
- Use deferred execution with .AsReaderLock(ReaderWriterLockSlim).

# Level 3: Maximum Performance
- Drop concurrent collections, use arrays.

**Comment by Aprogiena** [comment]
Hi. First of all, thanks for the effort of getting us closer to real async code. Really appreciate that! So I very much welcome the introduction of the real AsyncLock. 

Now as for your posts here, there are several things I disagree with and one very major thing I am completely missing.

The thing that I'm very much missing in such a guideline is that first of all, you always need to document your contract. If you are working with a shared resource, you have to describe, how it can be touched. 

One of the big disagreements with what you wrote I have is using of concurrent collections. I would say - strictly never use concurrent collections. 

These two things I've just mention can be demonstrated on the code of BlockPuller. This was the first thing I touched in the code when I joined the project. BlockPuller back then was using 3 concurrent collections and had no comments whatsoever, so no one really knew what the contracts were. The only thing that we knew at that point was that there is an error in the BlockPuller. 

At that time we did not even have a good log coverage, so I had to spend great amount of time of reverse engineering that code to find out what it actually does, what are the contracts and where the problem was.

There were multiple race conditions and the major problem we were looking for was caused exactly because concurrent collections were used. Those collections needed to be kept in sync, but that is impossible to do that with just concurrent collections and nothing else. However, because those collections are concurrent, they invite less experienced devs in multithreading code to use them to fix their concurrency problems. That's exactly why they should never be used. There are situations where you can use concurrent collections safely. But exactly because it is not obvious, they should never be used. Another reason for that is that when you use concurrent collection, your contracts are implicit and you would most likely tend not to document your contract (it would not even make much sense). 

Therefore for maximum security, strictly no use of concurrent collections.

--------

Then you say for better performance, use RW locks instead of lock/AL. That is imho wrong - esp. in case of the lock. Lock is very fast and actually I'm missing another thing here - the guideline should be "keep your critical sections as short as possible - i.e. lock the smallest part of the code you can". RW locks are heavy. They are much heavier than the lock. And they start to be efficient only when certain conditions are met. However, just like concurrent collections, RW locks seems suitable for everything, so people tend to use them regardless of the context. I agree with this post - https://stackoverflow.com/a/4217893/3835864 - which says that you should really consider the ratio between readers and writers and also the length of the critical section. I actually think it is quite rare to find a well designed code that uses RW lock and it would be justified.

--------

I'm also missing Interlocked based synchronization, which should outperform anything, but can't always be used.

---------

I don't understand what you mean by using arrays. So I would like to ask you for detailed explanation of that part.

--------

I would also suggest to strictly avoid .AsLocked or .AsReaderLock constructs - i.e. the thing that you describe in Thread-Safe Enumeration chapter in the first post. To me, this construct seems flawed from the readability point of view. However, I'm new to this construct, so maybe I am just missing the point of this one, so if you could present some real life examples on where it would be beneficial to use it, I may change my mind about it. But for the first look, this seems like another thing that is just calling for a disaster. 

The primary source of rejecting of that is that it seems to attempt to hide the real functionality and thus make the code unreadable, as you quoted:

> A great thing about foreach (and, by extension, LINQ) is that it correctly executes the Dispose() method of the enumerator. That is, foreach actually becomes a try-finally statement, where the enumerator is created, then iterated inside a try block, and disposed in finally.

For me this is quite ridiculous statement. This is not a great thing, this is terrible thing. This means that you write something, but you need to be aware that under the hood there is whole machinery that does something that is not obvious, which is exact opposite of what I'm trying to promote with have the code doing just what it says in the simplest way possible so that anyone can understand it even if their experience is not that great as yours. It is not very difficult to write a code that does all different side-effects that only the author recognizes. The difficult part is to write the code that everyone can read and check and understand and extend if necessary.

I would agree with avoiding deferred execution though.

**Comment by nopara73** [comment]
Reflecting to @Aprogiena 's remarks.

### Concurrent Collections

> However, because those collections are concurrent, they invite less experienced devs in multithreading code to use them to fix their concurrency problems.   

Interesting, so you see this as a bug, rather than a feature.  

### RW locks

You mostly convinced me on this. That didn't occur to me. If others are on board I'll remove RW locks from the guidelines. If anything, with removing them code complexity will be reduced greatly.  

### Interlocked

I am not familiar with this. I'll read up on it.

### Arrays

That's the lowest level collection that we don't have similar concurrent collection. Direct memory management and other low level stuff are possible with them.  
Of course you will disagree, because you think using concurrent collections is not the way to go, but my thinking process was: changing from concurrent dictionary to simple dictionary for performance is stupid.  
If you'd be better off with arrays anyway, but you used concurrent collections, because you have nothing similar to an array or a List, then changing to an array or a list will result significant performance increase.

### AsLocked

> if you could present some real life examples on where it would be beneficial to use it

It is beneficial whenever you want to "stream a collection" in a thread safe way. Otherwise you (1) either don't use deferred execution (don't use yield return and always ToArray and ToList your linq) (2) or give up thread safety, delegate that to the caller.

>  this seems like another thing that is just calling for a disaster.

I agree. I never tried it. Nevertheless the above described benefit is tempting for me.

**Comment by dangershony** [comment]
>So I very much welcome the introduction of the real AsyncLock.
Hi hi the scheduler lock (previous AsyncLock) is the most pure way of handling synchronised code (where no locks need to be held).

I very much disagree with the ConcurrentCollection assertion, if you look at the puller code now its several time more complicated then it was when using ConcurrentDictionaries, developers that need to go and make changes their will find it much harder and will be much less confident in the changes when needing to navigate between 3 different locks.
I would rather try to find a way to mitigate race conditions using ConcurrentDictionaries before resulting to using locks.

My opinion is that a large percent of synchronisation code cases can be solved using ConcurrentDictionaries.

**Comment by nopara73** [comment]
@Aprogiena 

# RW locks

Thinking more about RW locks, the performance of the lock is less of an issue (In the post he says 5 times faster), because it's mitigated by the actual operations inside the lock.  
For example entering and exiting a lock might take 0.001 seconds with traditional locks and 0.005 seconds with RW locks, but the actual operations take 1 second.

**Comment by Aprogiena** [comment]
@nopara73 I'm not saying do not ever use RW locks. In multithreading programming, it is more like that you always need to know what you are doing. Such a general guideline to avoid lock and prefer RW lock instead is imho misleading. RW locks definitely do have their place in the code, but only if they are beneficial for the given situation. More often than not, simple lock will perform better. So I think it needs quite a lot of experience to use RW lock in a way that it actually makes sense.

**Comment by nopara73** [comment]
> Such a general guideline to avoid lock and prefer RW lock instead is imho misleading.  

No, I definitely not saying that. I would say Level 0 should be used 95% of the times.

**Comment by Aprogiena** [comment]
> I very much disagree with the ConcurrentCollection assertion, if you look at the puller code now its several time more complicated then it was when using ConcurrentDictionaries, developers that need to go and make changes their will find it much harder and will be much less confident in the changes when needing to navigate between 3 different locks.
> I would rather try to find a way to mitigate race conditions using ConcurrentDictionaries before resulting to using locks.

I couldn't disagree more :-) Actually each concurrent collection comes with its own lock. So previously, block puller used those 3 locks. Now there is 1 lock. So from the point of view on whether the design is cleaner or not, considering the number of locks used, it is now much cleaner and uses less locks.

However, I'm not saying that less locks is better. I'm saying that the previous block puller did not work. There were multiple race conditions in that code and I do blame using concurrent collections there. 

I would say that similarly to RW locks, using concurrent collection requires much more experience on this field, otherwise this would happen. It is not just block puller, we can see ConcurrentChain to be another example of that. It is designed to make it easy to work with it and that's correct approach except that not in case when it is against the correctness of the code.

**Comment by Aprogiena** [comment]
@nopara73 It is slightly misleading because of that caption "Better performance". Without further context, it seems that using lock perform better. I think it is very very hard to form such a guideline that would be useful. It seems to me that either one does have an experience with multithreading code, then the guideline is not needed, or not, in which case the guideline won't help.

I agree with @dangershony that we have extra sync. primitives implemented - that exclusive scheduler lock, so they also should be considered in such a guideline. 

However, in general, I'm not sure we will be able to make a sensible guideline. We can try, but we should not consider it a big failure if such a thing does not exist. 

For example, I can imagine a usual scenario in which you start with lock and if it is later needed and someone makes an analysis that it is beneficial, it could be upgraded with RW locks. This seems like a natural evolution of the code and making optimization when needed. In case of async critical sections, one would start with AsyncLock instead of lock,

**Comment by Aprogiena** [comment]
> Arrays
>
>That's the lowest level collection that we don't have similar concurrent collection. Direct memory management and other low level stuff are possible with them.
Of course you will disagree, because you think using concurrent collections is not the way to go, but my thinking process was: changing from concurrent dictionary to simple dictionary for performance is stupid.
If you'd be better off with arrays anyway, but you used concurrent collections, because you have nothing similar to an array or a List, then changing to an array or a list will result significant performance increase.

The reason of not to use concurrent dictionary is not a performance. The reason is that the code does not work correctly. I would call it a principle of defensive programming style. I'm still unsure what you mean with arrays in terms of multithreading programming. Some kind of sample code would help me understand what you try to say.

**Comment by Aprogiena** [comment]
> AsLocked

I would again avoid any guideline and simply think about each case separately. If there is every such a situation, let's discuss it in its own context. If we find it beneficial to use such an advanced construct, then OK, but it is probably to be very rare.

**Comment by Aprogiena** [comment]
@dangershony just realized that you were probably talking about lookahead block puller, while i was talking about block puller ... in LBP we do have 3 locks, but they were just introduced to fix the race conditions there, not saying that the end result is super nice, but again, at least it works :)

**Comment by dangershony** [comment]
@Aprogiena the puller is a complicated component and it very much seems just using concurrent collections would not be enough to mitigate race conditions, but I was making it as an example of how much more complicated it will get when using locks instead of concurrent collections.
Indeed concurrent collections use locks internally but that is hidden away to the implementers.

I agree it hard to make guidelines as each case needs to be assessed independently.
We can have basic guidelines:

- Use the concurrent collections for simple synchronization. 
- More complex cases use `lock` or `asynclock`
- Other scenarios create an issue to discuss options.

**Comment by nopara73** [comment]
@dangershony Seems good to me.  

Another note. Stephen Cleary's AsyncEx.Coordination nuget has an AsyncLock, that can bot Lock and LockAsync. Maybe consider adding it and remove Toub's AsyncLock.

**Comment by Aprogiena** [comment]
OK, in which case I would put a big warning, that you can use concurrent collections only if: **THE COLLECTION IS PRIVATE AND IT IS THE ONLY COLLECTION IN THAT CLASS AND THERE IS NO CRITICAL LOGIC BASED ON ANY INFORMATION ABOUT THE STATE OF THE COLLECTION**

so there are two things - it should be only one collection, which means if there are two concurrent collections, you need extra lock to maintain integrity of data between them

the second is that even with just one concurrent collection, we did have race conditions bugs that look like this:

```
if (collection.Count() > 0)
{
    // something with collection like 
    item = collection.First();
    // but even any other logic that works with data integrity or whatever
}
```

this is a bug because the collection can be emptied just after we check that Count is not 0.

This is why I say we should avoid concurrent collection completely, because these mistakes are common - both of them, the two or more collections being used without additional lock or logic based on status of collection that is no longer valid after the check.

**Comment by dangershony** [comment]
Yeah this is a bug indeed, I agree its not 100% strait forward even when using concurrent ns.
But errors such as above are a result of not understanding concurrent collections, one should understand the component they are working with.

**Comment by nopara73** [comment]
I'd argue, way more bugs born from misusing locks, than misusing concurrent collections.

**Comment by Aprogiena** [comment]
@nopara73 i think this is your personal opinion just as mine is the opposite, we probably don't and won't have any data to sufficiently support either side, so let's have this one undecided :)

**Comment by Aprogiena** [comment]
One funny example from `LookaheadBlockPuller` code - `this.Chain` is the concurrent collection here:

```
...
            if (this.lookaheadLocation == null && !this.Chain.Contains(this.location))
            {
                this.logger.LogTrace("(-)[REORG]");
                return;
            }

            if (this.lookaheadLocation != null && !this.Chain.Contains(this.lookaheadLocation))
                this.lookaheadLocation = null;

            ChainedBlock lookaheadBlock = this.lookaheadLocation ?? this.location;
            ChainedBlock nextLookaheadBlock = this.Chain.GetBlock(Math.Min(lookaheadBlock.Height + this.ActualLookahead, this.Chain.Height));
            if (nextLookaheadBlock == null)
                return;

            ChainedBlock fork = nextLookaheadBlock.FindFork(lookaheadBlock);
...
```

Is anyone here able to argue about correctness of this code? 
Consider that after the first if `if (this.lookaheadLocation == null && !this.Chain.Contains(this.location))` the chain may contain `this.location` again. But since we exit the method, it is probably not a big deal. But then the second if has this `!this.Chain.Contains(this.lookaheadLocation)` and it does not exit from the method, so it looks like the code after that relies on that (or does it?). And again, this can become false just after it was evaluated to true.

Then we've got `nextLookaheadBlock = this.Chain.GetBlock` and if that is not null, it seems like that block is on the best chain. But just after we check for null, it may no longer be on the best chain. So then we find a fork point of this block vs `lookaheadBlock`. And given the all possible combinations we have here, what does it really mean?

So, to be honest, I have no idea what that code does. I would need to enumerate all possible combinations of what could happen because `this.Chain` can be changed on the background at any time. 

This is the reason why I'm trying to open discussion on getting rid of ConcurrentChain because I don't believe anyone can understand what the code that is using it actually does. 

If this was all enclosed in some kind of critical section or session, suddenly you would have invariants you could rely on and not this concurrent collection that can move any time.

**Comment by wintercooled** [comment]
Does anyone have any feeling on this? I have implemented a class as a Lazy
loaded (thread safe) singleton. Within there a ConcurrentDictionary with
locking is used to add and read from the dictionary. From all the documents
I can find this is both thread and race condition safe. Example code:

public sealed class ChaumianTumbler
    {
// Singleton instance
// IMPORTANT:   Lazy initialization is used for the _instance field, not
for performance
//              reasons but to ensure that the instance creation is
threadsafe.
//              Lazy initialization is thread-safe, but it doesn't protect
everything
//              within the class after creation - i.e. you must lock things
held in it
//              like collections etc. before accessing them.
private readonly static Lazy<ChaumianTumbler> _instance = new
Lazy<ChaumianTumbler>(() => new ChaumianTumbler());
private readonly ConcurrentDictionary<int, string> _exampleDictionary = new
ConcurrentDictionary<int, string>();
private readonly object _updateExampleDictionaryLock = new object();
private volatile bool _updatingExampleDictionary = false;

private ChaumianTumbler()
{
// Put any code to initliase collections with items etc. here.
}

public static ChaumianTumbler Instance
{
get
{
return _instance.Value;
}
}

//Example of adding to the collection/dictionary:
public void AddToExampleDictionary(int aNumber, string aString)
{
lock (_updateExampleDictionaryLock)
{
if (!_updatingExampleDictionary)
{
_updatingExampleDictionary = true;

_exampleDictionary.TryAdd(aNumber, aString);
_updatingExampleDictionary = false;
}
}
}

...rest of class
}

Then used like:

ChaumianTumbler ct = ChaumianTumbler.Instance;

ct.AddToExampleDictionary(123, "test example");


This is based on a pattern I have used before with no issues.

I think it is easy enough to read and understand.

To read is pretty much the same pattern as AddToExampleDictionary.

Thanks
Matt.

**Comment by wintercooled** [comment]
....should have said - I don't know what context you are looking at this
(as in where the calling code sits in your architecture) - so the use of a
singleton to access the dictionaries may not be appropriate. Just an idea...

Thanks,
Matt.

**Comment by Aprogiena** [comment]
The code is not very well formatted ... but if I see well you are having ConcurrentDirectory there but you use `lock()` around it. So that is weird just by itself. The that `_updatingExampleDictionary` is weird as well.

**Comment by wintercooled** [comment]
Sorry yes - the code was pulled from an example, extra lines removed and
pasted into email.

The lock is added because in the original code it performs a call to .Count
and .Contains before .TryAdd and although individual operations may be
thread-safe with ConcurrentDictionry/Collection sequences of operations are
not - as was mentioned in previous comments I think.

Anyway - I don't know the context so ignore me ;-)

**Comment by Aprogiena** [comment]
Yes, that is correct. Therefore, why to use concurrent dictionary in the first place? 
Anyway, this question you sent is off-topic to this discussion.

**Comment by wintercooled** [comment]
In relation to the topic @nopara73 raised and to answer 'why to use
concurrent dictionary in the first place?' - According to performance tests
of the new data structures like ConcurrentDictionary etc. (that are
specifically designed to simplify thread-safe access to shared data and
increase the performance and scalability of multi-threading applications
over locking)...

http://download.microsoft.com/download/B/C/F/BCFD4868-1354-45E3-B71B-B851CD78733D/PerformanceCharacteristicsOfThreadSafeCollection.pdf

"For read-heavy scenarios that require a thread-safe dictionary, the
ConcurrentDictionary(TKey,TValue) is the best choice" (over locked
Dictionary)

"In a multi-threaded scenario that requires frequent updates to a shared
dictionary,
ConcurrentDictionary(TKey,TValue) can provide modest benefits." (over
locked Dictionary)

I am just noting that the original comment "To sum up: we still need to use
locks [over ConcurrentDictionary], because, we need performance." is
perhaps not the case based on the paper linked to unless you require only
concurrent reads with no writes.

The above pdf link shows that ConcurrentDictionary is better for
performance than using lock. But you would still have to use lock around
the ConcurrentDictionary if you were going to use sequence of operations on
the dictionary.

So I was suggesting an approach to use ConcurrentDictionary if you are
performing many individual actions like a read or update but wrap sequenced
operations with a lock to prevent bugs - that is all I was trying to get
over.

But yes - I do not know the context of the target code in question. I was
just trying to contribute to the discussion.

Thanks anyway.

**Comment by Aprogiena** [comment]
This was actually a good contribution, thanks :-)

And just as with RW locks, most of the time, if you decided to use ConcurrentDictionary because of performance, you would very much misuse it.

Imho, one should always start with simplest approach and optimize performance only if necessary later. And for me, simplest does mean to avoid concurrent collection. This is where we are different with other guys, who consider using concurrent collections as the simpler way.

**Comment by Aprogiena** [comment]
Last minor note about that lock over CD. Imho that's bogus in most scenarios. It would have to be quite special case that such a construction would outperform something.

**Comment by wintercooled** [comment]
I generally favour the simplest approach and to quote the original: "We
started out having the plain old familiar lock. It's usage is
straightforward, it works well."

I'd just stick with that then, but yes, I don't know the context so i'll
leave you guys to it ;-)

**Comment by dangershony** [comment]
This is a good discussion but I think we can close it.
