### ISSUE TITLE
[Static flags in NStratis] Get rid of the static flags in NStratis

### ISSUE THREAD

**Issue by dangershony** [stratisproject/StratisBitcoinFullNode#676]
The two static properties are used to control serialisation of trx and blocks, they are also used in various other places.
```
                Transaction.TimeStamp = false;
                Block.BlockSignature = false;
```

This task is about making those flags none static.

**Comment by quantumagi** [comment]
Currently when creating a new Block, BlockHeader or Transaction we are not passing any arguments to qualify the network-specific serialization that these objects and their contained objects may undergo.

For this reason we would ideally be passing options to the constructors of these objects or any object that act as a repository for these objects. The assumption is that these flags would be pretty much fixed on network level, so that all objects in a repository would share the same set of flags.

**Comment by dangershony** [comment]
Using Options will work for serialisation, we can even use Network instead and pass Network in to the IBitcoinSerializer for determining serialisation flags.
How ever the biggest problem is hashing the block id, this will require passing Options in the constructor of Block which I am not the biggest fan of.

Another approach I had in mind, and I am not sure its the right one, is to use Network to get the block id so we will expose a method on network `network.GetBlockId(BlockHeader blockHeader)` that takes a block and use that every where, we could also use this approach for a trx, its very common practice that serialization is not done inside the component itself.

**Comment by quantumagi** [comment]
Given what you are suggesting there are two options:
1) Relay the TransactionOptions down the call hierarchy so that we can serialize objects and resolve block ids at the required points.
2) Relay the Network object down the call hierarchy for the same purpose.

In both cases serialization will still happen as before - with both approaches providing the required information to replace the static flags. 

The first approach aligns better with the current coding paradigm. I.e. not passing parent objects to child objects.  In contrast the current approach is minimalist - i.e. passing just enough information to child objects in the form of flags. In either case, Network or TransactionOptions, these values need to be reconstructed during deserialization. 

The primary objects that require these flags being passed are: Network, Block/BlockHeader and Transaction. Each of these would have a "TransactionOptions" (or "Network") member. Due to the network/options being associated with the BitcoinStream or repositories they are available to the deserialization methods of all the relevant objects.

Many of the serialization methods are already taking a TransactionOptions parameter. If we use an additional Network parameter then that would have to be added to these methods for reasons similar to the existence of the TransactionOptions parameter.

To get a feel for the number of changes involved (and this is the only way) I have attempted both methods and the number of files that require changes are basically the same. More than expected, but most files have one or two changes. The most changes occur in BitcoinSerializable and BitcoinStream for relaying purposes. Also a significant number of small changes are required for POS related test cases to pass the network or transaction options. For POW tests it is easy to default the transaction options - not so much if we decide to use Network..

**Comment by dangershony** [comment]
Right, Passing something in the constructor will indeed solve the problem (you also need to remember that the Protocol messages create transactions.

So a third approach where we use Network/Options to get the block/transaction hash (or also the serialisation of those types) is not a viable possibility?

If we pass the Network/TrasnactionOption in the BitcoinStream that solves the problem of serialisation (we will need though to pass Network in the constructor of BitcoinStream every where.

But we still don't solve the problem of the BlockHeader.GetHash()

**Comment by quantumagi** [comment]
The payload messages are serializing via BitcoinStream so any transactions or other objects being serialized would be getting their options from the stream.

We can pass Network to the BitcoinStream but we would be recording the Network.TransactionOptions.

In the "BlockSignature" case the BlockHeader.GetHash() uses ToBytes() which would look as follows:

```
		public static byte[] ToBytes(this IBitcoinSerializable serializable, ProtocolVersion version = ProtocolVersion.PROTOCOL_VERSION,
            TransactionOptions options = TransactionOptions.All)
		{
            if (serializable is IHaveTransactionOptions)
                options |= (serializable as IHaveTransactionOptions).GetTransactionOptions();

            MemoryStream ms = new MemoryStream();
            var bms = new BitcoinStream(ms, true)
            {
                ProtocolVersion = version,
                TransactionOptions = options
            };
			serializable.ReadWrite(bms);
			return ToArrayEfficient(ms);
		}
```

"GetTransactionOptions" would be returning either TransactionOptions.POSAll or TransactionOptions.All.

**Comment by dangershony** [comment]
I would like to talk more about the approach.
We have it seems several approachs

Determining serialisation (and block hashing) 
- With a flag in the object itself.
- Using a flag in the serialzier instance (seems the favoured approach) but I would probably not use TransactionOptions but rather get direct access to Network or ConsensusOptions
- Use an external class to serialize (for example `Network.SerializeTransaction)` or `Network.GetBlockHash`
- Use inheritance

@Aprogiena suggested we should think of the future requirements we will have and it may very well be that future networks will need to have different transaction and Block structures all together.

This brings inheritance to as a prime candidate.

**Lets discuss inheritance for a bit.**

How would we go about using `Block`, `BlockHeader` and `Transaction` in the node if we had to have, for now, two types of Blocks (and Transactions).
A block has the additional BlockSignature property and a Transaction has the additional TimeStamp property.

If we had a to change our code to have a `TransactionBase` and `BlockBase` and the current `Transaction` and `Block` will inherit form that base classes (we can rename to PowBlock and PowTransaction but probably as a later task) then have a new PosBlock and PosTransaction that have those additional fields.

How would this effect the current code base?
I presume the `TxPayload` will now have to look like this `TxPayload<TransactionBase>` and we would have to somehow register the correct TrasnactionType on the creation on the NetworkPeer itself

We might find we need to do things like

```
 var builder = new NetworkBuilder()
                .SetName("StratisTest")
                .SetConsensus(consensus)
                .SetMagic(magic)
                .SetBlockType<PosBlock>
                .SetTransactionType<PosTransactoin>
                .SetGenesis(genesis)
                .SetPort(26178)
                ...
```
The default will be the current `Transaction` I guess (not `TransactionBase`)

**Comment by quantumagi** [comment]
Yep we should consider using inheritance. It is important that we all feel comfortable with whatever solution we come up with. Although ay approach would seem better than the current one I am not sure the number of changes would be less in the final count though. The only thing we are certain about right now are the number of changes in the TransactionOption approach. If however, we can implement inheritance in a more gradual manner then that would be a plus point. I expect we would still have similar issues though in getting the required information through the blind spots in the call hierarchy - and that's the main reason for all the changes.
We would be facing the same issues in a different guise.
Note that a combined approach will also work. Adding a different class to avoid passing an extra parameter can easily be added to what we have now.

**Comment by quantumagi** [comment]
An inheritance approach may look something like this:

```
    public enum NetworkOption
    {
        IsProofOfStake
    }

    public class NetworkOptions
    {
        Func<NetworkOption, int, object> callback;

        public NetworkOptions(Func<NetworkOption, int, object> callback)
        {
            this.callback = callback;
        }

        public bool GetOption(NetworkOption option, int blockHeight = 0)
        {
            return (bool)this.callback(option, blockHeight);
        }
    }

    public static class StratisNetwork
    {
        public static NetworkOptions NetworkOptions = null;

        static StratisNetwork()
        {
            NetworkOptions = new NetworkOptions((option, height) => { return true; });
        }
    }

    public static class BitcoinNetwork
    {
        public static NetworkOptions NetworkOptions = null;

        static BitcoinNetwork()
        {
            NetworkOptions = new NetworkOptions((option, height) => { return false; });
        }
    }

    public abstract class Transaction
    {
        public NetworkOptions NetworkOptions { get; set; }
        public Transaction(bool isStratis)
        {
            this.NetworkOptions = isStratis ? StratisNetwork.NetworkOptions : BitcoinNetwork.NetworkOptions;
        }
    }

    public class StratisTransaction:Transaction        
    {
        public StratisTransaction():base(true)
        {
        }
    }

    public class BitcoinTransaction : Transaction
    {
        public BitcoinTransaction() : base(false)
        {
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var tx = new StratisTransaction();
            Debug.Assert(tx.NetworkOptions.GetOption(NetworkOption.IsProofOfStake) == true);
            var ty = new BitcoinTransaction();
            Debug.Assert(ty.NetworkOptions.GetOption(NetworkOption.IsProofOfStake) == false);
        }
    }
```

**Comment by Aprogiena** [comment]
When mentioning inheritance, I was thinking slightly differently. You still have some kind of network options here, which I wanted to avoid completely.

Especially I wanted to avoid this:
```
        public Transaction CreateTransaction()
        {
            return this.NetworkOptions.GetOption(NetworkOption.IsProofOfStake) ?
                new POSTransaction(this.NetworkOptions) as Transaction: 
                new POWTransaction(this.NetworkOptions) as Transaction;
        }
```

The way I wanted to avoid it is to have a base class of a transaction (or block, but let's talk about tx only now) and a class based on that would be a stratis transaction (and another could be e.g. segwit transaction etc.) So the base class would serialize to a non-segwit bitcoin tx format. The stratis transaction would then inject its special fields into that serialization. 

Would that work?

**Comment by quantumagi** [comment]
Having a Stratis transaction vs a Segwit transaction seems to be mixing apples and pears. Also, I think we will run into combinatorial explosion class-wise if we attempt to do this and the number of options increase. My thinking is that we either have a Stratis network/block/transaction or a Bitcoin network/block/transaction and combine that with options. When we register objects fields for serialization we can provide (1) the field order, (2) masks over the options to determine if a field serializes or not. What do you think?

**Comment by Aprogiena** [comment]
I don't think we will have explosion because no one said StratisTransaction has to be sealed.
So SmartContractTransaction could just be derrived from StratisTransaction. 

I'm not sure what you mean with mixing apples and pears, because we have in serialization code such an 
`if (witSupported)` and if we instead have this SegWitTransaction, this could be handled in its serialization and such an if would not be there in the base raw old BitcoinTransaction class

**Comment by dangershony** [comment]
We need to understand the different scenarios we may have.

**Same network different types:**   
Witness for example is the ability to serialize a trx in two different ways on the same network (so you have a bitcoin transaction that can be serialized in two ways with-witness/without-witness).

**Different networks:**  
The second scenario is different serialization networks, stratis/bitcoin/smartcontract-sidechian etc..
Stratis adds a timestamp filed to the serialized payload that will always be there, but stratis may still have different types of transactions segwit/no-segwit/some-additional-property  


This two possibilities are handled differently, for example if a network has only one Transaction type its simple for the Node.cs to know what to deserialize to and internally the trx will know how to populate its fields, this also goes inline with the current protocol code where deserialization id determined during the deserialization processes. 

If the same blockchain has 3 different types of trx how do we know what to deserialize a payload in to?
Unless we temper with the protocol messages (which perhaps we should) currently the TransactionPayload is determined as so
```
    [Payload("tx")]
    public class TxPayload : BitcoinSerializablePayload<Transaction>
    {
        public TxPayload()
        {
        }
       ..
    }
```
To introduce inheritance we would need to allow more trx types such as
```
    [Payload("cstx")]
    public class TxPayload : BitcoinSerializablePayload<SmartContractTransaction>
    {
        public TxPayload()
        {
        }
       ..
    }
```
In case of POS the payload is the same so we would register a new payload to the Node.cs 
```
    [Payload("tx")]
    public class PosTxPayload : BitcoinSerializablePayload<PosTransaction>
    {
        public PosTxPayload()
        {
        }
       ..
    }
```
Same goes for Block.

@quantumagi suggested a hybrid approach and I am supporting that.

We keep the current approach where a transaction can internally determine flow using some options (like how witness is done).

But also allow to add new TransactionTypes and use inheritance in the case of POS because the structure are very similar to POW
*And if we use a PosTransaction that inherits from PowTransaction we can still use the TransactionBuilder*

I believe, this approach will give us the most freedom we need .

**Comment by Aprogiena** [comment]
I have no stronger opinion here, so I'm OK with whatever you agree on.

**Comment by dangershony** [comment]
If we are ocnsidering the `Network<NetworkOptions>` -> `Network<Stratis>` then @bokobza should be involved as he is looking in this area as well with making Settings and Network more generic.

**Comment by quantumagi** [comment]
I.e.:

```
    public class NetworkOptions
    {
        public uint flags;
    }

    public class Stratis : NetworkOptions
    {
        public Stratis()
        {
            this.flags = 1234;
        }
    }

    public class Bitcoin : NetworkOptions
    {
        public Bitcoin()
        {
            this.flags = 4321;
        }
    }

    public class HasNetworkOptions<T> where T : NetworkOptions, new()
    {
        public virtual T Options { get; set; } = new T();
    }

    public class Network<T> : HasNetworkOptions<T> where T : NetworkOptions, new()
    {
        public Block<T> CreateBlock()
        {
            return new Block<T>();
        }
    }

    public class Block<T> : HasNetworkOptions<T> where T : NetworkOptions, new()
    {
        public POSTransaction<T> CreatePOSTransaction()
        {
            return new POSTransaction<T>() { Options = this.Options };
        }

        public POWTransaction<T> CreatePOWTransaction()
        {
            return new POWTransaction<T>() { Options = this.Options };
        }
    }

    public class Transaction<T> : HasNetworkOptions<T> where T : NetworkOptions, new()
    {
    }

    public class POSTransaction<T> : Transaction<T> where T : NetworkOptions, new()
    {
        public POSTransaction()
        {
            this.Options.flags |= 987; // Some flag indicating this is POS
        }
    }

    public class POWTransaction<T> : Transaction<T> where T : NetworkOptions, new()
    {
        public POWTransaction()
        {
        }
    }

    public class Repo<T> : HasNetworkOptions<T> where T : NetworkOptions, new()
    {
        public Block<T> GetBlock(int blockHeight)
        {
            return new Block<T>() { };
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var stratis = new Network<Stratis>();
            var bitcoin = new Network<Bitcoin>();

            var block = stratis.CreateBlock();
            var t1 = block.CreatePOSTransaction();
            var t2 = block.CreatePOWTransaction();

            var t3 = new POSTransaction<Stratis>();
            var block2 = new Block<Stratis>();
            var t4 = block2.CreatePOWTransaction();
        }
    }

```

**Comment by quantumagi** [comment]
Would it be sufficient to have a default set of options per combination of transaction type and network type? I.e. how far will that get us?

So as if we state:

var tx = new POSTransaction<Stratis>

, we are really providing two pieces: (1) the transaction _type_ and (2) the network _type_. If we need to strip out the "witness" flag then maybe that is just a (3) local processing option determined by processing context - i.e. not something we need to worry about in a broader sense?

**Comment by dangershony** [comment]
This is probably not so correct `var tx1 = new Transaction<Bitcoin>();`
How do we create a new trx in code (or from serializer) if the code is locked to a network?

If we do indeed go down a generic block and transaction then we could be much more creative

Then why not specify the header as a generic and the trx `new Block<THeader, TTransaction>()`

I also dont fully understand `IHaveNetworkOptions` its just used to wrap serializers right?

**Comment by quantumagi** [comment]
The code is locked to "class Bitcoin:NetworkOptions" - not to a network.

The line of code you are quoting will work as is:

By using Transaction<Bitcoin> we are creating a Transaction object that carries a NetworkOptions object of type Bitcoin (derived from NetworkOptions) internally.

This means the Transaction object can instantiate an object of type "Bitcoin" (NetworkOptions) and then call GetNetworkOptions on that options object.

Although the above will work, and will probably be used a lot in tests, it is probably better to have methods on the parent objects for creating the child objects. That way the parent objects are in a better position to influence the options of the child objects as we are allowing here:

```
        public T GetNetworkOptions(SerializationType type = SerializationType.Disk,
            ProtocolVersion version = ProtocolVersion.PROTOCOL_VERSION) 
        { 
             return this.parent?.GetNetworkOptions(type, version) ?? new T(); 
        }
```

IHaveNetworkOptions is an interface containing the above method.

**Comment by MithrilMan** [comment]
Hey!
Just a question, why not using a TransactionFactory?
Having a TransactionFactory that's responsible to create a Transaction instance, and having that TransactionFactory specified during Network configuration, would allow you to use DI and you can then resolve the dependency to obtain the right transaction

you could have a ITransactionFactory<Network> interface and register its implementation during the network configuration

You could even reference that transaction factory in the network instance (using DI or explicit parameter, but of course DI is more flexible, like you did in the Features constructors) and then you can have a method in the Network class that create the instance for you, without the need to reference the ITransactionService


this way you can bury the transaction serialization/deserialization logic in that factory class, that can access to the Network instance or any other service it needs

Sorry if i misunderstood the problem, it's late and I've been a lot out of stratis project :)

**Comment by quantumagi** [comment]
There is a lot of focus on the serialization/deserialization, as it is the ultimate goal, however the main problem is not that. The main problem as i see it is how to have the network context available to actually pass into such methods. The network context is often lost as methods call deeper methods and unfortunately we often need the network context deep down in the call hierarchy to perform serialization appropriately.  This is the reason that NetworkOptions were introduced - it should be one step better than passing the entire network object to all call depths. The idea is that the NetworkOptions should be handed over from Network -> Block -> Transaction -> etc. so that it is always available when it is necessary to determine serialization options.

**Comment by MithrilMan** [comment]
the concept of Service and ServiceLocator is what saves you in those scenario.
If you register the NetworkOption (and probably you already did, i have to check) allow you to be able to get it back when needed.

One way is using Dependency Injection as parameters in the object that need to use that, but in this scenario you should change every constructor of those object so this is something you actually maybe want to avoid, the other way is to expose a method, or a straight property like YourObject.NetworkOptions and populate it using the DI container, because DI containers can do more that just bind an interface to an instance of an object, they can instantiate the object you need using a factory class/method (i need to check what our current DI container allow)

This way, the factory method/class can populate the property of the object.
Easier is to register as a service within the container, a BlockFactory, TransactionFactory, etc... using default DI on constructor and delegating to them the burden of creating and instantiating a transaction and handling the serialization/deserialization (this mean at the end that Transaction become a mere DTO (data transfer object) without any logic

Depending on the choice it would require more or less refactory, but i think the main point should be to have a good codebase, foundation should be the main aspect to cover first, otherwise the project will be in trouble later

Anyway, and i say this as last because i don't like global/magic objects, another fast approach would be to have a public static singleton object where you can register all needed sharable resources, divided by an identification that can bind to any network (so you can have separate storage for separate network of the same type, if in future you want to run on a node 2 different stratislike nodes on two separate network)

"This Message Will Self Destruct In Five Seconds"
