### ISSUE TITLE
[ConsensusLoop] Signal block is inside lock

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#800]
When a block is accepted, we call `this.signals.SignalBlock(blockValidationContext.Block);` to propagate the information to all subscribers. This leads to serial execution of notification handlers in the subscribed component. This is all done while `consensusLock` is locked. 

This is probably not intentional, or is it?

Usual design of sending notification is that we do the processing inside a lock, set a local variable that we want to send notifications, release the lock and then send notifications outside of the lock.

**Comment by dangershony** [comment]
Yes in this case it is intentional.
The lock is more on the block being processed rather then on a resource , but this will also not have any effect on performance as the next block will not be pushed until signaling is complete (apart for mining operations but that is not effected anymore by perf). 

I am open to discuss that however, are we doing the signaling correctly?
Currently if one of the subscribers throws then consensus is effected (there is not try catch on the signaler)
Also signaling is not async so consensus is waiting for each subscriber.

I guess the best design approach is that each subscriber does not hold the execution but rather just push to some internal queue and release the signaler to continue (like in blockstore, and not like in wallet) however making the signaler async at the pushing side is rather dangerous as we then allow features to be careless as subscribers.

**Comment by Aprogiena** [comment]
so basically you are saying that you want a good ordering of blocks in subscribers, if that is true then yes, the lock is needed

it is a question whether we need that ordering or not, each subscriber could implement the logic of good ordering, but then it is probably easier to have it like this, although it should be documented that the lock is being held and that the subscribers should act as quickly as possible inside the notification handler

so should we want to keep the lock, we should at least document that condition

what you mentioned next is also valid, but i don't think those guys need to be async, rather what you say, if you can't process very quickly, just queue the notification and process in parallel thread, which is a good design then with ensured good ordering of blocks

but maybe you meant even better design, in which there is just one queue implemented by us (consensus loop) and this queue ensures good ordering and is calling the async subscribers, in which case this notification is outside of the lock (perfect), has good ordering (perfect), and subscribers are not limited to do anything and they are async (perfect, perfect)

so i'd suggest we do that, all previous things i've just mention seems inferior. so consensus loop would implement a new queue and a task (asyncloop?) would wait for an item to be available in the queue, it would remove it from the queue and signal to all subscribers (that's version 1), then version 2 could be making all subscribers async and we are done

**Comment by dangershony** [comment]
One thing is missing though is error handling if a subscriber throws how do we deal with that?
Using a queue decouples the behaviour of error handling from consensus and is that what we want?
We could always just shutdown the node on any error from a subscriber (probably this is what we should do).

Also if subscribers are anyway suppose to be quick and short then there is less of a reason to implement an intermediary queue.
Subscribers still need to be short and fast or they will delay other subscribers.

But yeah a queue is a superior solution indeed decoupling signalling from consensus, but as I said more dangerous for features to be careless.

**Comment by Aprogiena** [comment]
once it is in its own queue and thread, they can do long processing, no real problem with that
but we also can change that in a way that notification handlers of subscribers are called in parallel instead of in serial manner

if a subscriber crashes then it will be its problem and its problem only (if we get rid of the implementation that it is there now and create our own with exception handling and that parallelism)

**Comment by noescape00** [comment]
Fixed with activation merge.
