### ISSUE TITLE
Handling critical startup exceptions. 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#804]
As was suggested by @aprogiena there should be a way for handling critical startup exceptions that are not compatible with continuation of node starting process. Probably a new type of exception should be introduced for that and every component's startup rebuilt.

**Comment by Aprogiena** [comment]
Currently, the components are started with Start which returns void, so there is no how for the caller to see if the startup succeeded or not. We could either change the pattern to return bool and if something returned false then we would not continue with the startup. Or we can introduce a new type of exception that would be handled without reporting to the console.

The idea is not to crash to console, but give user a nice message when something bad happens due to misconfiguration or whatever is user's fault.

**Comment by dangershony** [comment]
Is it not like this already?

**Comment by bokobza** [comment]
https://github.com/stratisproject/StratisBitcoinFullNode/pull/1071 fixes the problem of the app getting stuck.
With this change, the app shows the exception as before, but the console stops.
I guess the way to fix this would be to internally catch the exception at the point of failure (like in the DBreeze constructor) and throw a nicer message.

**Comment by bokobza** [comment]
I think we can close this, the resolution is sufficient for now.
