### ISSUE TITLE
[BitcoinD] Can't be started, bad dependency

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#848]
dotnet run in BitcoinD folder:
```
crit: Stratis.Bitcoin.Configuration.NodeSettings[0]
      Feature MiningFeature cannot be configured because it depends on other features that were not registered
There was a problem initializing the node. Details: 'Dependency feature WalletFeature cannot be found.'
```

**Comment by dangershony** [comment]
@noescape00 I think just push something in this place can you confirm?

**Comment by noescape00** [comment]
>I think just push something in this place
I didn't quite get what you wanted to say here. Can you please elaborate? 

Regarding the issue: 
Mining feature has a ` .DependOn<WalletFeature>()`. It was added because mining feature project has a link to wallet project so when I was adding those I assumed that if we have a project linked then we probably depend on that feature to be enabled in the node.
@Aprogiena if you consider this one to be a false dependency just remove that depend on line from MiningFeature.cs

**Comment by mikedennis** [comment]
MiningFeature in general is not dependent upon wallet only POS is dependent on wallet (POW doesn't need wallet). If you look in MiningFeature.ValdiateDependencies() you will see the logic there.

**Comment by noescape00** [comment]
So I guess since this dependency is not correct for the whole mining feature it should be removed.

**Comment by mikedennis** [comment]
Yes... the ValidateDepencies should take care of it anyways.

**Comment by noescape00** [comment]
@Aprogiena would you like me to create a small PR with that removal or you'd like to include this in one of yours?

**Comment by Aprogiena** [comment]
only thing i want is that BitcoinD runs on master
if it does not work it is a bug
