### ISSUE TITLE
Launch argument do not override config. 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#863]
Config specified in stratis.conf treated with higher priority than launch arguments.

For example if I have stratis.conf like this: 
```
...
rpcport=57111
...
```

And launch node with -rpcport=57222 then config value 57111 still will be used.

**Comment by mikedennis** [comment]
From the current code it looks like the command line args are only added if they don't already exist in the conf file. 

Would just need to change this logic to overwrite instead of just add: https://github.com/stratisproject/StratisBitcoinFullNode/blob/master/src/Stratis.Bitcoin/Configuration/TextFileConfiguration.cs#L99-L110 

It makes logical sense to me to overwrite but was there a reason that .conf has priority?

**Comment by noescape00** [comment]
>Would just need to change this logic to overwrite instead of just add

Some commands like -addnode can be in multiple instances so if we want to add overriding we should specify what commands can be overridden and what can be duplicated. 
I think easier solution is to just search for commands from the end of the conf dictionary (config values are added first, then command line arguments) instead of from the start.

**Comment by mikedennis** [comment]
BTC loads command line args first then merges conf into those. Logic is here:
https://github.com/bitcoin/bitcoin/blob/master/src/util.cpp#L618-L645

**Comment by quantumagi** [comment]
Perhaps we can change it as follows:
- Normalize keys being inserted into the `args` array to either all have "-" or no "-".
- Give priority to the command line arguments by loading them first and then merging the file arguments. Allow multiple values for the same key during this process.
- When reading the value with `GetOrDefault` only return the first value if multiple values are present due to the above merging. Command line arguments would have precedence according to this approach.
- When reading the value with `GetAll` simply return all the values.

**Comment by bokobza** [comment]
So looking at the bitcoin code, they check
- command line args first https://github.com/bitcoin/bitcoin/blob/master/src/bitcoind.cpp#L66
- config file second https://github.com/bitcoin/bitcoin/blob/master/src/bitcoind.cpp#L98

and when they load the config file, they don't overwrite the arguments already present: https://github.com/bitcoin/bitcoin/blob/master/src/util.cpp#L664

**Comment by quantumagi** [comment]
The alternative approach is:
- Load config file first
- Append the file settings
- Always use the first recorded setting for a given key

The benefit of the above approach is that is only requires one dictionary of key/lists. 

When looking at the bitcoin code they require an additional dictionary `mapMultiArgs`:

'''
            if (mapArgs.count(strKey) == 0)
                mapArgs[strKey] = strValue;
            mapMultiArgs[strKey].push_back(strValue);
'''

**Comment by dangershony** [comment]
@bokobza is this fixed?
