### ISSUE TITLE
[PosMinting] Node should wait until connected to synced node

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/StratisBitcoinFullNode#921]
Currently the node is happy if it sees just one connected peer. However, if that peer is in IBD, the node is happy to mine a block even if it is itself well behind the tip.

**Comment by fassadlr** [comment]
@Aprogiena I can look at this issue?

We can potentially add a IBD flag in `NetworkPeerRequirement`, which the miner can then check?

**Comment by Aprogiena** [comment]
discuss with @noescape00 i think he was looking into this

**Comment by noescape00** [comment]
@fassadlr I haven't really started digging into it so I'm ok if you take this one. 

So far it looks like whole IBD needs to be refactored and added in a behavior that both peer and node has.

**Comment by noescape00** [comment]
@fassadlr let me know if you'd like to take this one or I can.

**Comment by fassadlr** [comment]
HI @noescape00, In #944 I started with some work on refactoring ChainState and it seems now that this issue is starting to look related to that one. I.e. the design behind IBD and IBlockDownloadState needs to be looked at again as there is quite a dependency graph that exists. @Aprogiena mentioned that the true provider of IBD is ConsensusLoop. See his comment:

https://github.com/stratisproject/StratisBitcoinFullNode/pull/944#issuecomment-352461605

So possibly if we solve this issue we can solve the issue with ChainState construction. Lets possibly look at this together?

**Comment by noescape00** [comment]
>So possibly if we solve this issue we can solve the issue with ChainState construction. Lets look at this together?

Sure. 

So let'y try outlining what we would like to achieve: 

1) We want to make a provider class of IBlockDownloadState to be the same for our node and for our view or the peer's node- that way we can implement logic behind IBlockDownloadState just once and have the ability to know if we are in IBD or any of our peers is. 
2) We don't want to pass a whole ConsensusManager just to know if we\peer is in IBD. 

Did I miss anything so far, @fassadlr?

**Comment by fassadlr** [comment]
> We want to make a provider class of IBlockDownloadState to be the same for our node and for our view or the peer's node- that way we can implement logic behind IBlockDownloadState just once and have the ability to know if we are in IBD or any of our peers is.
> We don't want to pass a whole ConsensusManager just to know if we\peer is in IBD.

SPOT on @noescape00! 🥇 

Once we have solved this dependency issue, we can remove the following dependencies:
1. FullNode dependency in ChainState
2. ChainState dependency in ConsensusManager

**Comment by Aprogiena** [comment]
as for 2. CS dependency in CM can be removed without doing anything, CM does have reference to ConsensusLoop and it is only using CS for getting CL's tip, it can directly get CL's tip from CL

**Comment by noescape00** [comment]
What we need to decide if the node is IBD: 

1) Tip of the chain. 
2) Checkpoints. 
3) NodeSettings.MaxTipAge constant. 
4) this.Network.Consensus.MinimumChainWork constant. 

So assuming that we and the peers are on the same network it's ok to use our stuff from 2),3),4) and we only need different Tips for our node and for the peer. 

It looks like ChainState is the right place to implement isIBD. Oh wait, it already does but it doesn't implement IBlockDownloadState interface. And in it's implementation it refers to 'this.fullNode.NodeService<IBlockDownloadState>' which is a ConsensusManager instance. Ok. 

So what we can do is removing IBlockDownloadState implementation from the ConsensusManager and do it instead only in the ChainState. And since our peers have ChainHeadersBehavior which have an inner chain state we can also get IBD state of the peer that way. 

Sounds right so far or I missed smth?

**Comment by noescape00** [comment]
>Once we have solved this dependency issue, we can remove the following dependencies:
>FullNode dependency in ChainState
>ChainState dependency in ConsensusManager

Yeah. Looks like those 2 will be automatically fixed by doing IBD check in another place.

**Comment by noescape00** [comment]
>as for 2. ChainState dependency in ConsensusManager can be removed without doing anything, ConsensusManager does have reference to ConsensusLoop and it is only using ConsensusManager for getting ConsensusLoop's  tip, it can directly get ConsensusLoop's tip from ConsensusLoop 

Good point, @Aprogiena.

**Comment by noescape00** [comment]
@Aprogiena @fassadlr let me know your opinion on this so we make sure we come to an agreement on how to execute this. 

@fassadlr when we agree on this would you like to make a PR and I review it or you'd prefer it to be the other way around?

**Comment by fassadlr** [comment]
@noescape00 be my guest and do the work on this :) We can review together.

My opinion on this (without knowing too much on the code) is that we should implement logic behind IBlockDownloadState, like you suggested. We can then inject whichever consumer that needs to know if the node is in IBD.

**Comment by noescape00** [comment]
Hmm. It looks like we can't add IBD check to the chain state since in that case ChainState will require a consensus loop which is a part of Consensus feature. And ChainState is a part of Stratis.Bitcoin project. 

Probably making a separate class like IBDStateProvider as a part of consensus feature will do the trick.
