### ISSUE TITLE
VS debugger would stop on handled exception if JustMyCode debugger option is enabled. 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/StratisBitcoinFullNode#928]
Example of code that would make dubuger stop: 
```
try
{
    await Task.Run(() => this.tcpClient.ConnectAsync(endPoint.Address, endPoint.Port).Wait(cancellation)).ConfigureAwait(false);
    this.Stream = this.tcpClient.GetStream();
}
catch (OperationCanceledException)
{
    this.logger.LogTrace("Connecting to '{0}' cancelled.", endPoint);
    this.logger.LogTrace("(-)[CANCELLED]");
    throw;
}
catch (Exception e)
{
    if (e is AggregateException) e = e.InnerException;
    this.logger.LogDebug("Error connecting to '{0}', exception: {1}", endPoint, e.ToString());
    this.logger.LogTrace("(-)[UNHANDLED_EXCEPTION]");
    throw e;
}
```

it would stop if code inside the `Task.Run` returns an exception even if this exception is supposed to be handled in the catch block.

**Comment by noescape00** [comment]
Apparently there are 2 solutions:
1. Disabling "Just My Code" option in the debugger options. But this way the debugging session would start much longer.
2. When you have such exceptions just click on the "Exception settings" in the windows that would pop up and disable "Break when this exception type is user-unhanded".
![exc](https://user-images.githubusercontent.com/10259355/34057143-e8040e44-e1e6-11e7-84a7-e415a6e07c7e.png)

So this issue have nothing to do with the actual code changes, just a tip for the devs who had to disable Just My Code and wait for long debugging sessions start.

**Comment by Aprogiena** [comment]
let's vote on whether this is an issue, let's have a scale
1 - non issue, don't fix (everyone can just setup their MSVS and that's fine)
2 - not a nice thing to have, but don't fix
3 - possibly an issue (ppl should not setup their MSVS, but making the code uglier because of this is not worth it, so fix only if there is other solution than implementing inner try/catch block)
4 - possibly an issue, should probably be fixed (if the code is uglier, well, so be it)
5 - definitely an issue (ppl should not setup their MSVS, it should work by default with default settings, we need to modify the code or project files or whatever)

i'm undecided between 3 and 4, so I vote for 3.5

**Comment by noescape00** [comment]
2

**Comment by Aprogiena** [comment]
let's ask @fassadlr @Neurosploit @dangershony @bokobza

**Comment by fassadlr** [comment]
Im between 4 and 5 :)

**Comment by Neurosploit** [comment]
Undecided between 2 and 4. However I'm very surprised it is unhandled as it's clearly caught in the method above. Is this a bug in the task runner by any chance or is this by design by MS?

**Comment by noescape00** [comment]
@Neurosploit this is by design by VS debugger, right.

**Comment by quantumagi** [comment]
I vote for 4.

**Comment by noescape00** [comment]
Ok, So now we agreed that this is an issue and we should perform a workaround to avoid the debugger pause on the default settings.

**Comment by bokobza** [comment]
Close because meh.
